/**
 * curatedCatalogData.ts
 * Curated world-class catalog for Books, Games, Standalone Movies, and TV Series.
 * Categorized by genres (Felsefe, Politika/Distopya, Klasikler, RPG, Suç & Drama, etc.)
 * with high-res artwork, ratings, pages, playtime, and synopsis.
 */

export interface CuratedBookItem {
  id: string;
  title: string;
  author: string;
  totalPages: number;
  releaseYear: number;
  category: string;
  genres: string[];
  coverUrl: string;
  rating: number; // Goodreads / 10
  synopsis: string;
}

export interface CuratedGameItem {
  id: string;
  title: string;
  developer: string;
  releaseYear: number;
  playtimeHours: number;
  platform: "PC" | "PlayStation" | "Xbox" | "Nintendo" | "Steam Deck" | "Other";
  category: string;
  genres: string[];
  coverUrl: string;
  rating: number; // Metacritic / 10
  synopsis: string;
}

export interface CuratedMovieItem {
  id: string;
  title: string;
  originalTitle?: string;
  director: string;
  releaseYear: number;
  runtimeMinutes: number;
  genres: string[];
  coverUrl: string;
  rating: number; // IMDb
  synopsis: string;
}

export interface CuratedTvItem {
  id: string;
  title: string;
  originalTitle?: string;
  creator: string;
  totalSeasons: number;
  totalEpisodes: number;
  releaseYear: number;
  endYear?: number;
  category: string;
  genres: string[];
  coverUrl: string;
  rating: number; // IMDb / 10
  synopsis: string;
}

/* ─────────────────────────────────────────────────────────────
   KİTAPLAR (CURATED BOOKS)
   ───────────────────────────────────────────────────────────── */
export const CURATED_BOOKS: CuratedBookItem[] = [
  // Distopya & Politika / Toplum
  {
    id: "book-1984",
    title: "1984",
    author: "George Orwell",
    totalPages: 328,
    releaseYear: 1949,
    category: "Politika & Distopya",
    genres: ["Distopya", "Politik", "Bilim Kurgu"],
    coverUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=500&q=80",
    rating: 8.9,
    synopsis: "Büyük Birader'in gözetimi altındaki Okyanusya'da Winston Smith'in hakikat ve özgürlük arayışı.",
  },
  {
    id: "book-hayvan-ciftligi",
    title: "Hayvan Çiftliği",
    author: "George Orwell",
    totalPages: 152,
    releaseYear: 1945,
    category: "Politika & Distopya",
    genres: ["Politik Hiciv", "Alegori", "Klasik"],
    coverUrl: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=500&q=80",
    rating: 8.7,
    synopsis: "İnsan efendilerine isyan eden hayvanların eşitlik vaadiyle başlayıp yeni bir diktatörlüğe dönüşen hikayesi.",
  },
  {
    id: "book-cesur-yeni-dunya",
    title: "Cesur Yeni Dünya",
    author: "Aldous Huxley",
    totalPages: 272,
    releaseYear: 1932,
    category: "Politika & Distopya",
    genres: ["Distopya", "Bilim Kurgu", "Felsefi"],
    coverUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=500&q=80",
    rating: 8.6,
    synopsis: "Acı ve kederin yapay zevklerle yok edildiği, teknolojik ve biyolojik kast sistemine dayalı bir gelecek.",
  },
  {
    id: "book-fahrenheit-451",
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    totalPages: 208,
    releaseYear: 1953,
    category: "Politika & Distopya",
    genres: ["Distopya", "Bilim Kurgu"],
    coverUrl: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=500&q=80",
    rating: 8.5,
    synopsis: "Kitapların yasaklandığı ve itfaiyecilerin kitap yaktığı bir dünyada Guy Montag'ın uyanışı.",
  },
  {
    id: "book-korluk",
    title: "Körlük",
    author: "José Saramago",
    totalPages: 336,
    releaseYear: 1995,
    category: "Politika & Distopya",
    genres: ["Distopya", "Alegori", "Toplumsal Psikoloji"],
    coverUrl: "https://images.unsplash.com/photo-1507842229458-772989b52a12?auto=format&fit=crop&w=500&q=80",
    rating: 9.0,
    synopsis: "Bilinmeyen bir şehirde aniden patlak veren 'beyaz körlük' salgını ve insan doğasının en çıplak halinin ortaya çıkışı.",
  },
  {
    id: "book-biz",
    title: "Biz",
    author: "Yevgeni Zamyatin",
    totalPages: 224,
    releaseYear: 1924,
    category: "Politika & Distopya",
    genres: ["Distopya", "Öncü Bilim Kurgu", "Politik"],
    coverUrl: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=500&q=80",
    rating: 8.7,
    synopsis: "1984 ve Cesur Yeni Dünya'ya ilham veren; insanların cam evlerde numaralarla yaşadığı Tek Devlet ütopyası.",
  },

  // Felsefe & Düşünce
  {
    id: "book-kendime-dusunceler",
    title: "Kendime Düşünceler",
    author: "Marcus Aurelius",
    totalPages: 200,
    releaseYear: 180,
    category: "Felsefe & Düşünce",
    genres: ["Stoacılık", "Antik Felsefe", "Kişisel Gelişim"],
    coverUrl: "https://images.unsplash.com/photo-1505664194779-8beaceb93744?auto=format&fit=crop&w=500&q=80",
    rating: 9.1,
    synopsis: "Roma İmparatoru ve filozof Marcus Aurelius'un içsel huzur, erdem, dayanıklılık ve Stoacı yaşam rehberi.",
  },
  {
    id: "book-sokratesin-savunmasi",
    title: "Sokrates'in Savunması",
    author: "Platon",
    totalPages: 88,
    releaseYear: -399,
    category: "Felsefe & Düşünce",
    genres: ["Antik Felsefe", "Ahlak", "Klasik"],
    coverUrl: "https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&w=500&q=80",
    rating: 8.8,
    synopsis: "Gençleri yoldan çıkardığı ve tanrılara inanmadığı iddiasıyla Atina mahkemesine çıkarılan Sokrates'in tavizsiz duruşu.",
  },
  {
    id: "book-boyle-buyurdu-zerdust",
    title: "Böyle Buyurdu Zerdüşt",
    author: "Friedrich Nietzsche",
    totalPages: 360,
    releaseYear: 1883,
    category: "Felsefe & Düşünce",
    genres: ["Varoluşçuluk", "Felsefi Şiir", "Üstinsan"],
    coverUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=500&q=80",
    rating: 9.1,
    synopsis: "Zerdüşt'ün dağdan inerek 'Üstinsan' ve geleneksel ahlakın ötesine geçme felsefesini insanlara anlatışı.",
  },
  {
    id: "book-sisifos-soyleni",
    title: "Sisifos Söyleni",
    author: "Albert Camus",
    totalPages: 160,
    releaseYear: 1942,
    category: "Felsefe & Düşünce",
    genres: ["Absürdizm", "Varoluşçuluk", "Felsefe"],
    coverUrl: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=500&q=80",
    rating: 8.9,
    synopsis: "Hayatın anlamsızlığı karşısında başkaldırı, intihar sorunsalı ve her gün taşı zirveye yuvarlayan Sisifos'un mutluluğu.",
  },
  {
    id: "book-devlet",
    title: "Devlet",
    author: "Platon",
    totalPages: 372,
    releaseYear: -375,
    category: "Felsefe & Düşünce",
    genres: ["Siyaset Felsefesi", "Adalet", "Mağara Alegorisi"],
    coverUrl: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=500&q=80",
    rating: 8.9,
    synopsis: "İdeal toplum, adalet nedir sorusu, filozof krallar ve meşhur Mağara Alegorisi ile Batı düşüncesinin temeli.",
  },
  {
    id: "book-denemeler",
    title: "Denemeler",
    author: "Michel de Montaigne",
    totalPages: 320,
    releaseYear: 1580,
    category: "Felsefe & Düşünce",
    genres: ["Hümanizm", "Kişisel Deneme", "Klasik"],
    coverUrl: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=500&q=80",
    rating: 8.8,
    synopsis: "'Kendimi anlatıyorum' diyerek insan doğasını, dostluğu, korkuyu, ölümü ve bilgeliği tarafsızca inceleyen başyapıt.",
  },

  // Klasikler & Dünya / Türk Edebiyatı
  {
    id: "book-suc-ve-ceza",
    title: "Suç ve Ceza",
    author: "Fyodor Dostoyevski",
    totalPages: 687,
    releaseYear: 1866,
    category: "Klasikler & Edebiyat",
    genres: ["Psikolojik Roman", "Klasik", "Felsefi"],
    coverUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=500&q=80",
    rating: 9.3,
    synopsis: "Yoksul öğrenci Raskolnikov'un ahlak sınırlarını aşarak işlediği cinayet ve ardından gelen vicdani yıkım.",
  },
  {
    id: "book-karamazov-kardesler",
    title: "Karamazov Kardeşler",
    author: "Fyodor Dostoyevski",
    totalPages: 840,
    releaseYear: 1880,
    category: "Klasikler & Edebiyat",
    genres: ["Felsefi Roman", "Psikolojik", "Klasik"],
    coverUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=500&q=80",
    rating: 9.5,
    synopsis: "Bir baba cinayeti etrafında Tanrı'nın varlığı, ahlak, adalet ve kardeşlerin farklı dünya görüşleri çatışması.",
  },
  {
    id: "book-donusum",
    title: "Dönüşüm",
    author: "Franz Kafka",
    totalPages: 96,
    releaseYear: 1915,
    category: "Klasikler & Edebiyat",
    genres: ["Varoluşçuluk", "Modernist", "Klasik"],
    coverUrl: "https://images.unsplash.com/photo-1532012164546-f432f2e3777f?auto=format&fit=crop&w=500&q=80",
    rating: 8.9,
    synopsis: "Bir sabah bunaltıcı düşlerden uyanan Gregor Samsa'nın kendisini dev bir böceğe dönüşmüş bulması.",
  },
  {
    id: "book-yabanci",
    title: "Yabancı",
    author: "Albert Camus",
    totalPages: 112,
    releaseYear: 1942,
    category: "Klasikler & Edebiyat",
    genres: ["Absürdizm", "Klasik", "Felsefi"],
    coverUrl: "https://images.unsplash.com/photo-1495640388908-05fa85288e61?auto=format&fit=crop&w=500&q=80",
    rating: 8.8,
    synopsis: "Meursault'nun toplumun yapmacık ahlak kurallarına karşı sergilediği dürüstlük ve absürt kayıtsızlık.",
  },
  {
    id: "book-satranc",
    title: "Satranç",
    author: "Stefan Zweig",
    totalPages: 84,
    releaseYear: 1942,
    category: "Klasikler & Edebiyat",
    genres: ["Psikolojik", "Novella", "Klasik"],
    coverUrl: "https://images.unsplash.com/photo-1529699211952-734e80c4d42b?auto=format&fit=crop&w=500&q=80",
    rating: 9.1,
    synopsis: "Gestapo tecridinde aklını sadece zihninde oynadığı satranç hamleleriyle koruyan Dr. B'nin gemideki büyük maçı.",
  },
  {
    id: "book-kurk-mantolu-madonna",
    title: "Kürk Mantolu Madonna",
    author: "Sabahattin Ali",
    totalPages: 160,
    releaseYear: 1943,
    category: "Klasikler & Edebiyat",
    genres: ["Türk Edebiyatı", "Psikolojik Aşk", "Klasik"],
    coverUrl: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&w=500&q=80",
    rating: 9.1,
    synopsis: "Raif Efendi'nin içine kapanık görünümünün ardında yatan Berlin günleri ve Maria Puder'e duyduğu unutulmaz aşk.",
  },
  {
    id: "book-saatleri-ayarlama",
    title: "Saatleri Ayarlama Enstitüsü",
    author: "Ahmet Hamdi Tanpınar",
    totalPages: 384,
    releaseYear: 1961,
    category: "Klasikler & Edebiyat",
    genres: ["Türk Edebiyatı", "Hiciv & İroni", "Toplumsal Değişim"],
    coverUrl: "https://images.unsplash.com/photo-1508057198894-247b23fe5ade?auto=format&fit=crop&w=500&q=80",
    rating: 9.0,
    synopsis: "Doğu ve Batı arasında bocalayan Türk modernleşmesini bürokrasi ve zaman kavramı üzerinden hicveden eşsiz roman.",
  },
  {
    id: "book-tutunamayanlar",
    title: "Tutunamayanlar",
    author: "Oğuz Atay",
    totalPages: 724,
    releaseYear: 1972,
    category: "Klasikler & Edebiyat",
    genres: ["Postmodern", "Türk Edebiyatı", "Yabancılaşma"],
    coverUrl: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=500&q=80",
    rating: 9.2,
    synopsis: "Selim Işık'ın intiharının izini süren Turgut Özben'in küçük burjuva dünyasını sorgulayarak 'tutunamayan' oluşu.",
  },
  {
    id: "book-ince-memed",
    title: "İnce Memed",
    author: "Yaşar Kemal",
    totalPages: 436,
    releaseYear: 1955,
    category: "Klasikler & Edebiyat",
    genres: ["Türk Edebiyatı", "Destansı", "İsyan & Adalet"],
    coverUrl: "https://images.unsplash.com/photo-1509023464722-18d996393ca8?auto=format&fit=crop&w=500&q=80",
    rating: 9.3,
    synopsis: "Çukurova'da zalim ağalara karşı dağa çıkarak ezilen köylülerin efsanevi koruyucusu haline gelen İnce Memed.",
  },
  {
    id: "book-beyaz-zambaklar",
    title: "Beyaz Zambaklar Ülkesinde",
    author: "Grigory Petrov",
    totalPages: 144,
    releaseYear: 1923,
    category: "Klasikler & Edebiyat",
    genres: ["Toplumsal Kalkınma", "Eğitim", "İlham"],
    coverUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=500&q=80",
    rating: 8.9,
    synopsis: "Bataklıklar ülkesi Finlandiya'nın aydınları, öğretmenleri ve halkıyla nasıl zambaklar ülkesine dönüştüğünün destanı.",
  },
  {
    id: "book-kucuk-prens",
    title: "Küçük Prens",
    author: "Antoine de Saint-Exupéry",
    totalPages: 112,
    releaseYear: 1943,
    category: "Klasikler & Edebiyat",
    genres: ["Felsefi Masal", "Klasik", "Dostluk"],
    coverUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=500&q=80",
    rating: 9.3,
    synopsis: "'İnsan ancak yüreğiyle baktığı zaman doğruyu görebilir; gerçeğin mayası gözle görülmez.'",
  },

  // Bilim Kurgu & Spekülatif
  {
    id: "book-dune",
    title: "Dune",
    author: "Frank Herbert",
    totalPages: 712,
    releaseYear: 1965,
    category: "Bilim Kurgu & Spekülatif",
    genres: ["Bilim Kurgu", "Uzay Operası", "Politik"],
    coverUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=500&q=80",
    rating: 9.2,
    synopsis: "Çöl gezegeni Arrakis'te baharat savaşı, kehanetler ve Paul Atreides'in mesihliğe yükselişi.",
  },
  {
    id: "book-vakif",
    title: "Vakıf",
    author: "Isaac Asimov",
    totalPages: 288,
    releaseYear: 1951,
    category: "Bilim Kurgu & Spekülatif",
    genres: ["Bilim Kurgu", "Psikotarih", "Klasik"],
    coverUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=500&q=80",
    rating: 8.9,
    synopsis: "Matematikçi Hari Seldon'ın galaktik imparatorluğun çöküşünü ve 30.000 yıllık karanlığı 1.000 yıla indirme planı.",
  },
  {
    id: "book-otostopcu",
    title: "Otostopçunun Galaksi Rehberi",
    author: "Douglas Adams",
    totalPages: 224,
    releaseYear: 1979,
    category: "Bilim Kurgu & Spekülatif",
    genres: ["Bilim Kurgu", "Mizah", "Macera"],
    coverUrl: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=500&q=80",
    rating: 8.8,
    synopsis: "Dünya yok edilmeden hemen önce dostu Ford Prefect ile uzaya kaçan Arthur Dent'in absürt yolculuğu.",
  },

  // Tarih, Biyografi & Popüler Bilim
  {
    id: "book-sapiens",
    title: "Sapiens: Hayvanlardan Tanrılara",
    author: "Yuval Noah Harari",
    totalPages: 412,
    releaseYear: 2011,
    category: "Tarih & Antropoloji",
    genres: ["Antropoloji", "Tarih", "Popüler Bilim"],
    coverUrl: "https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&w=500&q=80",
    rating: 9.0,
    synopsis: "Önemsiz bir primat türü olan Homo sapiens'in bilişsel, tarım ve bilim devrimleriyle gezegenin hakimi oluşu.",
  },
  {
    id: "book-kozmos",
    title: "Kozmos",
    author: "Carl Sagan",
    totalPages: 400,
    releaseYear: 1980,
    category: "Tarih & Antropoloji",
    genres: ["Astronomi", "Popüler Bilim", "Evren Felsefesi"],
    coverUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=500&q=80",
    rating: 9.4,
    synopsis: "Bizler yıldız tozuyuz; evrenin kendisini tanımasının bir yoluyuz. 15 milyar yıllık kozmik serüven.",
  },
  {
    id: "book-zamanin-kisa-tarihi",
    title: "Zamanın Kısa Tarihi",
    author: "Stephen Hawking",
    totalPages: 256,
    releaseYear: 1988,
    category: "Tarih & Antropoloji",
    genres: ["Kozmoloji", "Fizik", "Popüler Bilim"],
    coverUrl: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=500&q=80",
    rating: 9.0,
    synopsis: "Büyük Patlama'dan kara deliklere, zamanın yönünden evrenin nihai sırlarına uzanan büyüleyici yolculuk.",
  },

  // Psikoloji & Anlam
  {
    id: "book-insanin-anlam-arayisi",
    title: "İnsanın Anlam Arayışı",
    author: "Viktor E. Frankl",
    totalPages: 168,
    releaseYear: 1946,
    category: "Psikoloji & Anlam",
    genres: ["Logoterapi", "Psikoloji", "Varoluşsal"],
    coverUrl: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=500&q=80",
    rating: 9.2,
    synopsis: "Nazi toplama kamplarından sağ kurtulan psikiyatr Frankl'ın 'yaşamak için bir nedeni olan her türlü nasıla katlanır' tezine dayalı logoterapisi.",
  },
  {
    id: "book-akis-flow",
    title: "Akış (Flow)",
    author: "Mihaly Csikszentmihalyi",
    totalPages: 320,
    releaseYear: 1990,
    category: "Psikoloji & Anlam",
    genres: ["Pozitif Psikoloji", "Odaklanma", "Mutluluk"],
    coverUrl: "https://images.unsplash.com/photo-1507842229458-772989b52a12?auto=format&fit=crop&w=500&q=80",
    rating: 8.8,
    synopsis: "Zamanı ve benliği unutturan derin odaklanma deneyiminin (akış halinin) optimal insan mutluluğundaki anahtar rolü.",
  },
];

/* ─────────────────────────────────────────────────────────────
   DİZİLER (CURATED TV SHOWS - SORTED BY ACCLAIM & POPULARITY)
   ───────────────────────────────────────────────────────────── */
export const CURATED_TV_SHOWS: CuratedTvItem[] = [
  // Suç & Drama
  {
    id: "tv-breaking-bad",
    title: "Breaking Bad",
    creator: "Vince Gilligan",
    totalSeasons: 5,
    totalEpisodes: 62,
    releaseYear: 2008,
    endYear: 2013,
    category: "Suç & Drama",
    genres: ["Suç", "Drama", "Gerilim"],
    coverUrl: "https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
    rating: 9.5,
    synopsis: "Ölümcül kanser teşhisi alan lise kimya öğretmeni Walter White'ın ailesinin geleceğini güvenceye almak için metamfetamin imparatorluğuna dönüşmesi.",
  },
  {
    id: "tv-better-call-saul",
    title: "Better Call Saul",
    creator: "Vince Gilligan & Peter Gould",
    totalSeasons: 6,
    totalEpisodes: 63,
    releaseYear: 2015,
    endYear: 2022,
    category: "Suç & Drama",
    genres: ["Suç", "Hukuk", "Drama"],
    coverUrl: "https://image.tmdb.org/t/p/w500/fC2HDm5t0kHsf7YbyHKQCfdUtm6.jpg",
    rating: 9.0,
    synopsis: "Dürüst bir avukat olmaya çalışan Jimmy McGill'in suç dünyasının aranan avukatı Saul Goodman'a dönüşüm trajedisi.",
  },
  {
    id: "tv-the-sopranos",
    title: "The Sopranos",
    creator: "David Chase",
    totalSeasons: 6,
    totalEpisodes: 86,
    releaseYear: 1999,
    endYear: 2007,
    category: "Suç & Drama",
    genres: ["Mafya", "Psikolojik Drama", "Suç"],
    coverUrl: "https://image.tmdb.org/t/p/w500/rweIrveL43TaxUN0akQEaAXL6x0.jpg",
    rating: 9.2,
    synopsis: "New Jersey mafya babası Tony Soprano'nun aile hayatı, organize suç ve panik atakları sebebiyle psikiyatristiyle yaptığı seanslar.",
  },
  {
    id: "tv-the-wire",
    title: "The Wire",
    creator: "David Simon",
    totalSeasons: 5,
    totalEpisodes: 60,
    releaseYear: 2002,
    endYear: 2008,
    category: "Suç & Drama",
    genres: ["Gerçekçi Suç", "Polisiye", "Sosyolojik"],
    coverUrl: "https://image.tmdb.org/t/p/w500/4lbclFySvugI51fwsyxBTOm4DqK.jpg",
    rating: 9.3,
    synopsis: "Baltimore şehrinde uyuşturucu ticareti, liman işçileri, belediye siyaseti, eğitim sistemi ve medyanın iç içe geçmiş kurumlar anatomisi.",
  },
  {
    id: "tv-peaky-blinders",
    title: "Peaky Blinders",
    creator: "Steven Knight",
    totalSeasons: 6,
    totalEpisodes: 36,
    releaseYear: 2013,
    endYear: 2022,
    category: "Suç & Drama",
    genres: ["Tarihi Suç", "Dönem Draması", "Gangster"],
    coverUrl: "https://image.tmdb.org/t/p/w500/vUUqzWa2LnHIVqkaKVlVGkVcTTW.jpg",
    rating: 8.8,
    synopsis: "1. Dünya Savaşı sonrasında Birmingham'da jiletli kasketleriyle dehşet saçan Shelby ailesi ve dahi liderleri Thomas Shelby.",
  },
  {
    id: "tv-true-detective",
    title: "True Detective",
    creator: "Nic Pizzolatto",
    totalSeasons: 4,
    totalEpisodes: 30,
    releaseYear: 2014,
    category: "Suç & Drama",
    genres: ["Polisiye", "Karanlık Gizem", "Felsefi"],
    coverUrl: "https://image.tmdb.org/t/p/w500/cuV2O53rBpZG33IP3YhpNjBgGMv.jpg",
    rating: 8.9,
    synopsis: "Louisiana bataklıklarında 17 yıla yayılan ritüel bir cinayeti soruşturan zıt karakterli iki dedektif: Rust Cohle ve Marty Hart.",
  },
  {
    id: "tv-fargo",
    title: "Fargo",
    creator: "Noah Hawley",
    totalSeasons: 5,
    totalEpisodes: 51,
    releaseYear: 2014,
    category: "Suç & Drama",
    genres: ["Kara Mizah", "Suç Antolojisi", "Gerilim"],
    coverUrl: "https://image.tmdb.org/t/p/w500/6flsC2y3q4R3kQpQJ7U7fQe2L5x.jpg",
    rating: 8.9,
    synopsis: "Minnesota'nın dondurucu kasabalarında sıradan insanların kaza ve açgözlülükle içine çekildiği kanlı ve absürt cinayetler.",
  },

  // Bilim Kurgu & Gerilim
  {
    id: "tv-dark",
    title: "Dark",
    creator: "Baran bo Odar & Jantje Friese",
    totalSeasons: 3,
    totalEpisodes: 26,
    releaseYear: 2017,
    endYear: 2020,
    category: "Bilim Kurgu & Gerilim",
    genres: ["Zaman Yolculuğu", "Gizem", "Felsefi Bilim Kurgu"],
    coverUrl: "https://image.tmdb.org/t/p/w500/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg",
    rating: 8.7,
    synopsis: "Alman kasabası Winden'da bir çocuğun kaybolmasıyla ortaya çıkan, dört ailenin nesiller boyu iç içe geçmiş 33 yıllık zaman döngüleri.",
  },
  {
    id: "tv-black-mirror",
    title: "Black Mirror",
    creator: "Charlie Brooker",
    totalSeasons: 6,
    totalEpisodes: 27,
    releaseYear: 2011,
    category: "Bilim Kurgu & Gerilim",
    genres: ["Distopya", "Teknoloji Hicvi", "Antoloji"],
    coverUrl: "https://image.tmdb.org/t/p/w500/7RumFHk423PocqQ1k1Ld1y9g0sE.jpg",
    rating: 8.7,
    synopsis: "İleri teknolojinin insan doğası, ahlak, sosyal medya ve mahremiyet üzerindeki karanlık ve rahatsız edici yansımaları.",
  },
  {
    id: "tv-stranger-things",
    title: "Stranger Things",
    creator: "The Duffer Brothers",
    totalSeasons: 4,
    totalEpisodes: 34,
    releaseYear: 2016,
    category: "Bilim Kurgu & Gerilim",
    genres: ["80'ler Nostaljisi", "Doğaüstü", "Macera"],
    coverUrl: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    rating: 8.7,
    synopsis: "1980'lerde Hawkins kasabasında bir çocuğun kaybolması, gizli hükümet deneyleri ve 'Baş Aşağı' evreninden gelen yaratıklar.",
  },
  {
    id: "tv-severance",
    title: "Severance",
    creator: "Dan Erickson & Ben Stiller",
    totalSeasons: 1,
    totalEpisodes: 9,
    releaseYear: 2022,
    category: "Bilim Kurgu & Gerilim",
    genres: ["Kurumsal Distopya", "Psikolojik Gerilim", "Gizem"],
    coverUrl: "https://image.tmdb.org/t/p/w500/h259M0fL14B4XyFq4VzR6mGZJ1h.jpg",
    rating: 8.7,
    synopsis: "Lumon Industries çalışanlarının iş ve özel hayat anılarını cerrahi müdahaleyle iki ayrı kişiliğe bölen gizemli prosedür.",
  },
  {
    id: "tv-the-last-of-us",
    title: "The Last of Us",
    creator: "Craig Mazin & Neil Druckmann",
    totalSeasons: 1,
    totalEpisodes: 9,
    releaseYear: 2023,
    category: "Bilim Kurgu & Gerilim",
    genres: ["Kıyamet Sonrası", "Hayatta Kalma", "Dram"],
    coverUrl: "https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2V7JMrRI.jpg",
    rating: 8.8,
    synopsis: "Mantar enfeksiyonunun medeniyeti yok ettiği dünyada katılaşmış kaçakçı Joel ile insanlığın son umudu olabilecek Ellie'nin yolculuğu.",
  },

  // Tarih & Mini-Dizi
  {
    id: "tv-chernobyl",
    title: "Chernobyl",
    creator: "Craig Mazin",
    totalSeasons: 1,
    totalEpisodes: 5,
    releaseYear: 2019,
    endYear: 2019,
    category: "Tarih & Mini-Dizi",
    genres: ["Tarihi Felaket", "Gerilim", "Siyasi"],
    coverUrl: "https://image.tmdb.org/t/p/w500/hlLXt2tOPT6RRnjiUmoxyG9LTFi.jpg",
    rating: 9.4,
    synopsis: "1986 Çernobil Nükleer Santrali felaketi ve yalanların bedelini hayatlarıyla ödeyen cesur bilim insanları ve tasfiyeciler.",
  },
  {
    id: "tv-band-of-brothers",
    title: "Band of Brothers",
    creator: "Tom Hanks & Steven Spielberg",
    totalSeasons: 1,
    totalEpisodes: 10,
    releaseYear: 2001,
    endYear: 2001,
    category: "Tarih & Mini-Dizi",
    genres: ["2. Dünya Savaşı", "Kardeşlik", "Tarih"],
    coverUrl: "https://image.tmdb.org/t/p/w500/zTxm7kZ7hM4J2gN2e7h0p1v3r4u.jpg",
    rating: 9.4,
    synopsis: "Normandiya çıkarmasından Hitler'in Kartal Yuvası'na kadar savaşan Amerikan 101. Hava İndirme Easy Bölüğü'nün gerçek hikayesi.",
  },
  {
    id: "tv-the-queens-gambit",
    title: "The Queen's Gambit",
    creator: "Scott Frank",
    totalSeasons: 1,
    totalEpisodes: 7,
    releaseYear: 2020,
    endYear: 2020,
    category: "Tarih & Mini-Dizi",
    genres: ["Satranç", "Dönem Draması", "Büyüme"],
    coverUrl: "https://image.tmdb.org/t/p/w500/zU0htwkhNvBQdVSIKB9uf6hgIK2.jpg",
    rating: 8.5,
    synopsis: "Yetimhanede satranç dahisi olduğu keşfedilen Beth Harmon'ın bağımlılıklarıyla mücadele ederek dünya şampiyonluğuna yükselişi.",
  },

  // Fantastik & Macera
  {
    id: "tv-game-of-thrones",
    title: "Game of Thrones",
    creator: "David Benioff & D.B. Weiss",
    totalSeasons: 8,
    totalEpisodes: 73,
    releaseYear: 2011,
    endYear: 2019,
    category: "Fantastik & Macera",
    genres: ["Epik Fantazi", "Siyaset", "Orta Çağ"],
    coverUrl: "https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    rating: 9.2,
    synopsis: "Westeros'un Demir Tahtı için hanedanların verdiği acımasız entrika savaşları ve Kuzey'deki kadim Ak Gezen tehlikesi.",
  },
  {
    id: "tv-arcane",
    title: "Arcane",
    creator: "Christian Linke & Alex Yee",
    totalSeasons: 2,
    totalEpisodes: 18,
    releaseYear: 2021,
    category: "Fantastik & Macera",
    genres: ["Animasyon", "Steampunk", "Trajedi"],
    coverUrl: "https://image.tmdb.org/t/p/w500/fq2h0sT6N6y0E4r3rP2Q8g5r4q.jpg",
    rating: 9.0,
    synopsis: "Ütopik Piltover ile yeraltı şehri Zaun arasındaki uçurumda birbirine düşman kamplara savrulan iki yetim kız kardeş: Vi ve Jinx.",
  },
  {
    id: "tv-house-of-the-dragon",
    title: "House of the Dragon",
    creator: "Ryan Condal & George R.R. Martin",
    totalSeasons: 2,
    totalEpisodes: 18,
    releaseYear: 2022,
    category: "Fantastik & Macera",
    genres: ["Ejderhalar", "Veraset Savaşı", "Fantazi"],
    coverUrl: "https://image.tmdb.org/t/p/w500/t9XkeFsDh0vTgvO6apHRGlH9vXd.jpg",
    rating: 8.4,
    synopsis: "Game of Thrones olaylarından 200 yıl önce Targaryen hanedanını iç savaşa sürükleyen 'Ejderhaların Dansı' dönemi.",
  },

  // Komedi, Hiciv & Sosyal
  {
    id: "tv-succession",
    title: "Succession",
    creator: "Jesse Armstrong",
    totalSeasons: 4,
    totalEpisodes: 39,
    releaseYear: 2018,
    endYear: 2023,
    category: "Komedi & Hiciv",
    genres: ["Kara Mizah", "Medya Hanedanı", "Dram"],
    coverUrl: "https://image.tmdb.org/t/p/w500/77iZkI3nQ4cE8M8hL2bXyT3q9jV.jpg",
    rating: 8.9,
    synopsis: "Küresel medya devi Waystar RoyCo'nun yaşlanan kurucusu Logan Roy'un koltuğunu kapmak için çocuklarının sergilediği entrikalar.",
  },
  {
    id: "tv-the-office",
    title: "The Office (US)",
    creator: "Greg Daniels",
    totalSeasons: 9,
    totalEpisodes: 201,
    releaseYear: 2005,
    endYear: 2013,
    category: "Komedi & Hiciv",
    genres: ["Sitcom", "Mockumentary", "Ofis Mizahı"],
    coverUrl: "https://image.tmdb.org/t/p/w500/7DJKHzAi83BmQrWLrYY5qMm8pff.jpg",
    rating: 9.0,
    synopsis: "Scranton'daki Dunder Mifflin kağıt şirketinin eksantrik bölge müdürü Michael Scott ve çalışanlarının eğlenceli ofis hayatı.",
  },
  {
    id: "tv-fleabag",
    title: "Fleabag",
    creator: "Phoebe Waller-Bridge",
    totalSeasons: 2,
    totalEpisodes: 12,
    releaseYear: 2016,
    endYear: 2019,
    category: "Komedi & Hiciv",
    genres: ["Dördüncü Duvar", "Kara Komedi", "Dram"],
    coverUrl: "https://image.tmdb.org/t/p/w500/1X6G0OQvQpB7r3Q5b2Y4v8T9q.jpg",
    rating: 8.7,
    synopsis: "Londra'da yas, öfke ve yalnızlıkla baş etmeye çalışan, kameraya bakarak doğrudan seyirciyle konuşan zeki bir kadının hikayesi.",
  },
  {
    id: "tv-ted-lasso",
    title: "Ted Lasso",
    creator: "Jason Sudeikis & Bill Lawrence",
    totalSeasons: 3,
    totalEpisodes: 34,
    releaseYear: 2020,
    endYear: 2023,
    category: "Komedi & Hiciv",
    genres: ["Pozitif Komedi", "Futbol", "İlham"],
    coverUrl: "https://image.tmdb.org/t/p/w500/2LomkP7N0R8f0VbK6mK8x3qQ.jpg",
    rating: 8.8,
    synopsis: "İngiliz futbol takımı AFC Richmond'ı çalıştırmak üzere Londra'ya getirilen iyimser Amerikan futbolu koçu Ted Lasso.",
  },
  {
    id: "tv-rick-and-morty",
    title: "Rick and Morty",
    creator: "Dan Harmon & Justin Roiland",
    totalSeasons: 7,
    totalEpisodes: 71,
    releaseYear: 2013,
    category: "Komedi & Hiciv",
    genres: ["Animasyon", "Çoklu Evren", "Absürt Bilim Kurgu"],
    coverUrl: "https://image.tmdb.org/t/p/w500/cvhNj9eoRBe5SHbNk7ioRZ0Eh5v.jpg",
    rating: 9.1,
    synopsis: "Alkolik dahi bilim insanı Rick Sanchez ve saf torunu Morty'nin paralel boyutlar ve galaksiler arası çılgın maceraları.",
  },

  // Gizem & Zeka
  {
    id: "tv-sherlock",
    title: "Sherlock",
    creator: "Steven Moffat & Mark Gatiss",
    totalSeasons: 4,
    totalEpisodes: 13,
    releaseYear: 2010,
    endYear: 2017,
    category: "Gizem & Zeka",
    genres: ["Modern Dedektiflik", "Çıkarım Sanatı", "Gizem"],
    coverUrl: "https://image.tmdb.org/t/p/w500/7WTsnDMwk2T69x44gA3Jq04tTj5.jpg",
    rating: 9.1,
    synopsis: "21. yüzyıl modern Londra'sında akıllı telefonlar ve adli tıp yardımıyla en karmaşık davaları çözen dahi dedektif Sherlock Holmes.",
  },
  {
    id: "tv-mindhunter",
    title: "Mindhunter",
    creator: "Joe Penhall & David Fincher",
    totalSeasons: 2,
    totalEpisodes: 19,
    releaseYear: 2017,
    endYear: 2019,
    category: "Gizem & Zeka",
    genres: ["Seri Katiller", "FBI Profilleme", "Psikoloji"],
    coverUrl: "https://image.tmdb.org/t/p/w500/fbKE87mojpIETWepY1X6KnNeAcb.jpg",
    rating: 8.6,
    synopsis: "1970'lerin sonunda FBI'da tutuklu seri katillerle görüşerek modern kriminal profil çıkarma yöntemini kuran iki ajan.",
  },
];

/* ─────────────────────────────────────────────────────────────
   OYUNLAR (CURATED TOP GAMES - SORTED BY ACCLAIM)
   ───────────────────────────────────────────────────────────── */
export const CURATED_GAMES: CuratedGameItem[] = [
  // RPG & Açık Dünya
  {
    id: "game-rdr2",
    title: "Red Dead Redemption 2",
    developer: "Rockstar Games",
    releaseYear: 2018,
    playtimeHours: 50,
    platform: "PC",
    category: "RPG & Açık Dünya",
    genres: ["Açık Dünya", "Vahşi Batı", "Dram"],
    coverUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=500&q=80",
    rating: 9.7,
    synopsis: "Vahşi Batı çağının sonunda Van der Linde çetesinin sadık üyesi Arthur Morgan'ın kefaret ve hayatta kalma hikayesi.",
  },
  {
    id: "game-gta-v",
    title: "Grand Theft Auto V",
    developer: "Rockstar North",
    releaseYear: 2013,
    playtimeHours: 32,
    platform: "PC",
    category: "RPG & Açık Dünya",
    genres: ["Açık Dünya", "Aksiyon", "Suç"],
    coverUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=500&q=80",
    rating: 9.7,
    synopsis: "Los Santos şehrinde Michael, Franklin ve Trevor'ın bir dizi tehlikeli soygunla yeraltı dünyasını fethettiği başyapıt.",
  },
  {
    id: "game-zelda-botw",
    title: "The Legend of Zelda: Breath of the Wild",
    developer: "Nintendo",
    releaseYear: 2017,
    playtimeHours: 50,
    platform: "Nintendo",
    category: "RPG & Açık Dünya",
    genres: ["Açık Dünya", "Macera", "Keşif"],
    coverUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=500&q=80",
    rating: 9.7,
    synopsis: "100 yıllık uykusundan uyanan Link'in Hyrule Krallığı'nı Calamity Ganon'dan kurtarmak için sınırsız keşif yolculuğu.",
  },
  {
    id: "game-elden-ring",
    title: "Elden Ring",
    developer: "FromSoftware",
    releaseYear: 2022,
    playtimeHours: 60,
    platform: "PC",
    category: "RPG & Açık Dünya",
    genres: ["Souls-like", "Açık Dünya", "RPG"],
    coverUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=500&q=80",
    rating: 9.6,
    synopsis: "Arada Kalan Topraklar'da Elden Yüzüğü'nün parçalarını toplayarak yeni Elden Lordu olma mücadelesi.",
  },
  {
    id: "game-baldurs-gate-3",
    title: "Baldur's Gate 3",
    developer: "Larian Studios",
    releaseYear: 2023,
    playtimeHours: 75,
    platform: "PC",
    category: "RPG & Açık Dünya",
    genres: ["cRPG", "Sıra Tabanlı", "Zengin Hikaye"],
    coverUrl: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=500&q=80",
    rating: 9.6,
    synopsis: "Beynindeki Mind Flayer parazitinden kurtulmak isteyen bir grup maceracının Unutulmuş Diyarlar'daki kaderi.",
  },
  {
    id: "game-witcher-3",
    title: "The Witcher 3: Wild Hunt",
    developer: "CD PROJEKT RED",
    releaseYear: 2015,
    playtimeHours: 52,
    platform: "PC",
    category: "RPG & Açık Dünya",
    genres: ["Açık Dünya", "RPG", "Karanlık Fantazi"],
    coverUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=500&q=80",
    rating: 9.3,
    synopsis: "Rivyalı Geralt, kehanet çocuğu Ciri'yi Vahşi Av'dan önce bulmak için savaşın harap ettiği kıtada arayışa çıkar.",
  },
  {
    id: "game-skyrim",
    title: "The Elder Scrolls V: Skyrim",
    developer: "Bethesda Game Studios",
    releaseYear: 2011,
    playtimeHours: 35,
    platform: "PC",
    category: "RPG & Açık Dünya",
    genres: ["Açık Dünya", "RPG", "Fantastik"],
    coverUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=500&q=80",
    rating: 9.4,
    synopsis: "Ejderhaların geri döndüğü Skyrim topraklarında kadim güç Dragonborn olarak kaderine yürüyüş.",
  },
  {
    id: "game-persona-5-royal",
    title: "Persona 5 Royal",
    developer: "Atlus",
    releaseYear: 2020,
    playtimeHours: 102,
    platform: "PlayStation",
    category: "RPG & Açık Dünya",
    genres: ["JRPG", "Sosyal Simülasyon", "Sıra Tabanlı"],
    coverUrl: "https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=500&q=80",
    rating: 9.5,
    synopsis: "Tokyo'da gündüz lise öğrencisi, gece yozlaşmış yetişkinlerin kalplerindeki hazineleri çalan Hayalet Hırsızlar.",
  },
  {
    id: "game-mass-effect-le",
    title: "Mass Effect Legendary Edition",
    developer: "BioWare",
    releaseYear: 2021,
    playtimeHours: 60,
    platform: "PC",
    category: "RPG & Açık Dünya",
    genres: ["Bilim Kurgu", "RPG", "Seçim & Sonuç"],
    coverUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=500&q=80",
    rating: 9.0,
    synopsis: "Komutan Shepard'ın tüm galaksiyi organik yaşamı yok etmeye gelen Reaper tehdidine karşı birleştirme destanı.",
  },
  {
    id: "game-cyberpunk-2077",
    title: "Cyberpunk 2077",
    developer: "CD PROJEKT RED",
    releaseYear: 2020,
    playtimeHours: 30,
    platform: "PC",
    category: "RPG & Açık Dünya",
    genres: ["Cyberpunk", "Açık Dünya", "Aksiyon RPG"],
    coverUrl: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=500&q=80",
    rating: 8.6,
    synopsis: "Night City metropolünde ölümsüzlük çipini ele geçirmeye çalışan paralı asker V ve zihnindeki rockçı Johnny Silverhand.",
  },

  // Aksiyon & Macera
  {
    id: "game-god-of-war",
    title: "God of War (2018)",
    developer: "Santa Monica Studio",
    releaseYear: 2018,
    playtimeHours: 21,
    platform: "PlayStation",
    category: "Aksiyon & Macera",
    genres: ["Aksiyon", "İskandinav Mitolojisi", "Dram"],
    coverUrl: "https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?auto=format&fit=crop&w=500&q=80",
    rating: 9.4,
    synopsis: "Olimpos'un intikamını geride bırakan Kratos'un İskandinav diyarında oğlu Atreus ile çıktığı olgunlaşma serüveni.",
  },
  {
    id: "game-the-last-of-us-1",
    title: "The Last of Us Part I",
    developer: "Naughty Dog",
    releaseYear: 2013,
    playtimeHours: 16,
    platform: "PlayStation",
    category: "Aksiyon & Macera",
    genres: ["Kıyamet Sonrası", "Dram", "Gizlilik"],
    coverUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=500&q=80",
    rating: 9.5,
    synopsis: "Salgın sonrası harabeye dönen Amerika'da bir kaçakçı ile bağışık genç bir kızın hayatta kalma ve insanlık mücadelesi.",
  },
  {
    id: "game-uncharted-4",
    title: "Uncharted 4: A Thief's End",
    developer: "Naughty Dog",
    releaseYear: 2016,
    playtimeHours: 15,
    platform: "PlayStation",
    category: "Aksiyon & Macera",
    genres: ["Macera", "Hazine Avı", "Sinematik"],
    coverUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=500&q=80",
    rating: 9.3,
    synopsis: "Emekli hazine avcısı Nathan Drake'in kayıp korsan kolonisi Libertalia'yı bulmak için son büyük macerası.",
  },

  // Bulmaca, Platform & FPS
  {
    id: "game-portal-2",
    title: "Portal 2",
    developer: "Valve",
    releaseYear: 2011,
    playtimeHours: 9,
    platform: "PC",
    category: "Platform & Bulmaca",
    genres: ["Fizik Bulmacası", "Kara Mizah", "Bilim Kurgu"],
    coverUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=500&q=80",
    rating: 9.5,
    synopsis: "Aperture Science tesislerinde portal tabancası, yapay zeka GLaDOS ve sakar robot Wheatley ile akıl almaz bulmacalar.",
  },
  {
    id: "game-half-life-2",
    title: "Half-Life 2",
    developer: "Valve",
    releaseYear: 2004,
    playtimeHours: 15,
    platform: "PC",
    category: "Platform & Bulmaca",
    genres: ["FPS", "Bilim Kurgu", "Fizik Devrimi"],
    coverUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=500&q=80",
    rating: 9.6,
    synopsis: "Uzaylı istilası altındaki City 17'de levyesiyle direnişi ateşleyen teorik fizikçi Gordon Freeman'ın efsanesi.",
  },
  {
    id: "game-bioshock",
    title: "BioShock",
    developer: "2K Games",
    releaseYear: 2007,
    playtimeHours: 12,
    platform: "PC",
    category: "Platform & Bulmaca",
    genres: ["İmmersive Sim", "Distopya", "Felsefi FPS"],
    coverUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=500&q=80",
    rating: 9.6,
    synopsis: "Okyanus dibindeki ütopik Rapture şehrinin çöküşünde genetik mutasyonlar ve 'Would you kindly?' gizemi.",
  },
  {
    id: "game-doom-eternal",
    title: "DOOM Eternal",
    developer: "id Software",
    releaseYear: 2020,
    playtimeHours: 14,
    platform: "PC",
    category: "Platform & Bulmaca",
    genres: ["Hızlı FPS", "Aksiyon", "Metal Müzik"],
    coverUrl: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=500&q=80",
    rating: 8.8,
    synopsis: "Dünyayı cehennem ordularından temizlemek için tek kişilik ordu Doom Slayer'ın amansız ve ritmik savaşı.",
  },

  // Bağımsız / Indie
  {
    id: "game-disco-elysium",
    title: "Disco Elysium: The Final Cut",
    developer: "ZA/UM",
    releaseYear: 2019,
    playtimeHours: 22,
    platform: "PC",
    category: "Bağımsız / Indie",
    genres: ["Felsefi RPG", "Dedektiflik", "Politik"],
    coverUrl: "https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=500&q=80",
    rating: 9.7,
    synopsis: "Hafızasını kaybetmiş bir dedektifin Revachol şehrinde hem cinayeti çözmeye hem de kimliğini inşa etmeye çalıştığı edebiyat harikası.",
  },
  {
    id: "game-hades",
    title: "Hades",
    developer: "Supergiant Games",
    releaseYear: 2020,
    playtimeHours: 22,
    platform: "PC",
    category: "Bağımsız / Indie",
    genres: ["Rogue-like", "Yunan Mitolojisi", "Hızlı Aksiyon"],
    coverUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=500&q=80",
    rating: 9.3,
    synopsis: "Yeraltı dünyasının prensi Zagreus'un babası Hades'in diyarından kaçıp Olimpos Dağı'na ulaşma mücadelesi.",
  },
  {
    id: "game-hollow-knight",
    title: "Hollow Knight",
    developer: "Team Cherry",
    releaseYear: 2017,
    playtimeHours: 27,
    platform: "PC",
    category: "Bağımsız / Indie",
    genres: ["Metroidvania", "Atmosferik", "Zorlu"],
    coverUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=500&q=80",
    rating: 9.0,
    synopsis: "Hallownest'in terk edilmiş böcek krallığında karanlık enfeksiyonun kökenini arayan isimsiz şövalyenin serüveni.",
  },
  {
    id: "game-celeste",
    title: "Celeste",
    developer: "Maddy Makes Games",
    releaseYear: 2018,
    playtimeHours: 9,
    platform: "PC",
    category: "Bağımsız / Indie",
    genres: ["Hassas Platform", "Zihinsel Sağlık", "Bağımsız"],
    coverUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=500&q=80",
    rating: 9.2,
    synopsis: "Madeline'in kendi iç kaygılarıyla yüzleşerek Celeste Dağı'nın zirvesine tırmandığı duygu yüklü başyapıt.",
  },

  // Strateji & Simülasyon
  {
    id: "game-civ-6",
    title: "Sid Meier's Civilization VI",
    developer: "Firaxis Games",
    releaseYear: 2016,
    playtimeHours: 80,
    platform: "PC",
    category: "Strateji & Simülasyon",
    genres: ["4X", "Sıra Tabanlı", "Tarih & Medeniyet"],
    coverUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=500&q=80",
    rating: 8.8,
    synopsis: "Taş Devri'nden Bilgi Çağı'na medeniyetini kurup yöneterek dünya tarihine yön verme stratejisi.",
  },
];

/* ─────────────────────────────────────────────────────────────
   KÜLT FİLMLER (STANDALONE MASTERPIECES - SORTED BY IMDB ACCLAIM)
   ───────────────────────────────────────────────────────────── */
export const CURATED_MOVIES: CuratedMovieItem[] = [
  {
    id: "movie-godfather-1",
    title: "Baba",
    originalTitle: "The Godfather",
    director: "Francis Ford Coppola",
    releaseYear: 1972,
    runtimeMinutes: 175,
    genres: ["Suç", "Dram"],
    coverUrl: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    rating: 9.2,
    synopsis: "Corleone mafya ailesinin reisi Don Vito'dan oğlu Michael'a geçen güç, sadakat ve intikam savaşı.",
  },
  {
    id: "movie-shawshank",
    title: "Esaretin Bedeli",
    originalTitle: "The Shawshank Redemption",
    director: "Frank Darabont",
    releaseYear: 1994,
    runtimeMinutes: 142,
    genres: ["Dram", "Umut"],
    coverUrl: "https://image.tmdb.org/t/p/w500/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
    rating: 9.3,
    synopsis: "İşlemediği cinayetten ömür boyu hapse mahkum edilen Andy Dufresne'in 20 yıllık sabır, zeka ve dostluk hikayesi.",
  },
  {
    id: "movie-dark-knight",
    title: "Kara Şövalye",
    originalTitle: "The Dark Knight",
    director: "Christopher Nolan",
    releaseYear: 2008,
    runtimeMinutes: 152,
    genres: ["Aksiyon", "Suç", "Dram"],
    coverUrl: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    rating: 9.0,
    synopsis: "Batman, Teğmen Gordon ve Savcı Harvey Dent'in Gotham'ı anarşiye sürükleyen Joker'e karşı verdiği psikolojik sınav.",
  },
  {
    id: "movie-schindlers-list",
    title: "Schindler'in Listesi",
    originalTitle: "Schindler's List",
    director: "Steven Spielberg",
    releaseYear: 1993,
    runtimeMinutes: 195,
    genres: ["Biyografi", "Dram", "Tarih"],
    coverUrl: "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    rating: 9.0,
    synopsis: "2. Dünya Savaşı'nda binden fazla Yahudi'yi fabrikasında çalıştırarak Holokost'tan kurtaran Oskar Schindler'in gerçek öyküsü.",
  },
  {
    id: "movie-12-angry-men",
    title: "12 Öfkeli Adam",
    originalTitle: "12 Angry Men",
    director: "Sidney Lumet",
    releaseYear: 1957,
    runtimeMinutes: 96,
    genres: ["Dram", "Mahkeme"],
    coverUrl: "https://image.tmdb.org/t/p/w500/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg",
    rating: 9.0,
    synopsis: "Bir gencin cinayet davasında 12 jüri üyesinin tek bir odada önyargı, adalet ve vicdanla verdiği amansız tartışma.",
  },
  {
    id: "movie-pulp-fiction",
    title: "Ucuz Roman",
    originalTitle: "Pulp Fiction",
    director: "Quentin Tarantino",
    releaseYear: 1994,
    runtimeMinutes: 154,
    genres: ["Suç", "Kara Mizah"],
    coverUrl: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    rating: 8.9,
    synopsis: "Los Angeles yeraltı dünyasında iki kiralık katil, bir boksör ve bir mafya patronunun kesişen sürreal hikayeleri.",
  },
  {
    id: "movie-forrest-gump",
    title: "Forrest Gump",
    originalTitle: "Forrest Gump",
    director: "Robert Zemeckis",
    releaseYear: 1994,
    runtimeMinutes: 142,
    genres: ["Dram", "Romantik", "İlham"],
    coverUrl: "https://image.tmdb.org/t/p/w500/arw2VCBveWOVZr6pxd9XTd1TdQa.jpg",
    rating: 8.8,
    synopsis: "Düşük IQ'lu saf kalpli Forrest Gump'ın istemeden Amerikan tarihinin en önemli olaylarına yön veren dokunaklı hayatı.",
  },
  {
    id: "movie-fight-club",
    title: "Dövüş Kulübü",
    originalTitle: "Fight Club",
    director: "David Fincher",
    releaseYear: 1999,
    runtimeMinutes: 139,
    genres: ["Dram", "Gerilim"],
    coverUrl: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    rating: 8.8,
    synopsis: "Uykusuzluk çeken bir büro çalışanının karizmatik sabun satıcısı Tyler Durden ile kurduğu gizli yeraltı kulübü.",
  },
  {
    id: "movie-inception",
    title: "Başlangıç",
    originalTitle: "Inception",
    director: "Christopher Nolan",
    releaseYear: 2010,
    runtimeMinutes: 148,
    genres: ["Bilim Kurgu", "Aksiyon", "Gerilim"],
    coverUrl: "https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    rating: 8.8,
    synopsis: "İnsanların rüyalarına girerek sırlarını çalan dahi hırsız Dom Cobb'un bu kez zihne fikir ekleme (inception) görevi.",
  },
  {
    id: "movie-interstellar",
    title: "Yıldızlararası",
    originalTitle: "Interstellar",
    director: "Christopher Nolan",
    releaseYear: 2014,
    runtimeMinutes: 169,
    genres: ["Bilim Kurgu", "Dram", "Macera"],
    coverUrl: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    rating: 8.7,
    synopsis: "Yok olmanın eşiğindeki insanlık için yaşanabilir yeni bir gezegen aramak üzere solucan deliğinden geçen astronotlar.",
  },
  {
    id: "movie-goodfellas",
    title: "Sıkı Dostlar",
    originalTitle: "Goodfellas",
    director: "Martin Scorsese",
    releaseYear: 1990,
    runtimeMinutes: 145,
    genres: ["Biyografi", "Suç", "Dram"],
    coverUrl: "https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kcuD.jpg",
    rating: 8.7,
    synopsis: "Çocukluğundan beri gangster olmak isteyen Henry Hill'in mafya piramidinde yükselişi ve kaçınılmaz düşüşü.",
  },
  {
    id: "movie-seven",
    title: "Yedi",
    originalTitle: "Se7en",
    director: "David Fincher",
    releaseYear: 1995,
    runtimeMinutes: 127,
    genres: ["Suç", "Gizem", "Psikolojik Gerilim"],
    coverUrl: "https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVUO.jpg",
    rating: 8.6,
    synopsis: "Yedi ölümcül günahı motif olarak kullanan bir seri katilin peşindeki emekliliğe yakın dedektif Somerset ile fevri Mills.",
  },
  {
    id: "movie-spirited-away",
    title: "Ruhların Kaçışı",
    originalTitle: "Sen to Chihiro no Kamikakushi",
    director: "Hayao Miyazaki",
    releaseYear: 2001,
    runtimeMinutes: 125,
    genres: ["Animasyon", "Macera", "Fantastik"],
    coverUrl: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    rating: 8.6,
    synopsis: "Domuza dönüşen ebeveynlerini kurtarmak için ruhlar dünyasındaki hamamda çalışmak zorunda kalan küçük Chihiro'nun serüveni.",
  },
  {
    id: "movie-whiplash",
    title: "Whiplash",
    originalTitle: "Whiplash",
    director: "Damien Chazelle",
    releaseYear: 2014,
    runtimeMinutes: 107,
    genres: ["Dram", "Müzik", "Psikolojik"],
    coverUrl: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    rating: 8.5,
    synopsis: "Tarihin en iyi caz davulcusu olmak isteyen Andrew Neiman ile sınırları zorlayan acımasız orkestra şefi Terence Fletcher.",
  },
  {
    id: "movie-parasite",
    title: "Parazit",
    originalTitle: "Parasite (Gisaengchung)",
    director: "Bong Joon-ho",
    releaseYear: 2019,
    runtimeMinutes: 132,
    genres: ["Gerilim", "Kara Komedi", "Dram"],
    coverUrl: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    rating: 8.5,
    synopsis: "Yoksul Kim ailesinin zengin Park ailesinin evine birer birer sızmasıyla başlayan öngörülemez sınıf çatışması.",
  },
  {
    id: "movie-prestige",
    title: "Prestij",
    originalTitle: "The Prestige",
    director: "Christopher Nolan",
    releaseYear: 2006,
    runtimeMinutes: 130,
    genres: ["Dram", "Gizem", "Bilim Kurgu"],
    coverUrl: "https://image.tmdb.org/t/p/w500/bdN3gXu4E2nhR9v978R94iV7rV.jpg",
    rating: 8.5,
    synopsis: "19. yüzyıl Londra'sında en mükemmel ışınlanma numarasını yaratmak için birbirlerinin hayatını mahveden iki ilüzyonist.",
  },
  {
    id: "movie-gladiator",
    title: "Gladyatör",
    originalTitle: "Gladiator",
    director: "Ridley Scott",
    releaseYear: 2000,
    runtimeMinutes: 155,
    genres: ["Aksiyon", "Macera", "Dram"],
    coverUrl: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    rating: 8.5,
    synopsis: "Ailesi katledilen ve köle olarak satılan Romalı general Maximus'un Kolezyum'da imparatora karşı intikam arayışı.",
  },
];
