/**
 * movieSeriesData.ts
 * Curated database of iconic film series and cinematic franchises.
 * Provides high-resolution TMDB artwork, chronological and release order timelines,
 * IMDb ratings, phases, runtimes, and user progress synchronization helpers.
 */

import type { MediaItem, MovieSeries, MovieSeriesItem } from "@/types/media.js";

export const CURATED_MOVIE_SERIES: MovieSeries[] = [
  {
    id: "mcu",
    title: "Marvel Sinematik Evreni (MCU)",
    originalTitle: "Marvel Cinematic Universe",
    description:
      "Iron Man ile başlayıp Avengers: Endgame ve Multiverse sagasına uzanan, sinema tarihinin en büyük süper kahraman evreni.",
    bannerUrl:
      "https://images.unsplash.com/photo-1635805737707-575885ab0820?auto=format&fit=crop&w=1200&q=80",
    totalMovies: 34,
    averageRating: 7.7,
    genres: ["Süper Kahraman", "Bilim Kurgu", "Aksiyon", "Macera"],
    hasChronologicalOrder: true,
    items: [
      // Faz 1
      {
        id: "mcu-1",
        seriesId: "mcu",
        title: "Iron Man",
        originalTitle: "Iron Man",
        releaseYear: 2008,
        releaseOrder: 1,
        chronologicalOrder: 3,
        phaseOrArc: "Faz 1: Avengers Assembled",
        director: "Jon Favreau",
        runtimeMinutes: 126,
        imdbRating: 7.9,
        genres: ["Aksiyon", "Bilim Kurgu"],
        coverUrl: "https://image.tmdb.org/t/p/w500/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
        synopsis: "Tony Stark gelişmiş bir zırh takımı inşa eder ve terörizmle savaşmaya karar verir.",
      },
      {
        id: "mcu-2",
        seriesId: "mcu",
        title: "The Incredible Hulk",
        originalTitle: "The Incredible Hulk",
        releaseYear: 2008,
        releaseOrder: 2,
        chronologicalOrder: 4,
        phaseOrArc: "Faz 1: Avengers Assembled",
        director: "Louis Leterrier",
        runtimeMinutes: 112,
        imdbRating: 6.6,
        genres: ["Aksiyon", "Bilim Kurgu"],
        coverUrl: "https://image.tmdb.org/t/p/w500/gKzYx79y0AQTL4UAk1cBQJ3nvrm.jpg",
        synopsis: "Bruce Banner içindeki canavarı kontrol altına almaya çalışırken ordu peşine düşer.",
      },
      {
        id: "mcu-3",
        seriesId: "mcu",
        title: "Iron Man 2",
        originalTitle: "Iron Man 2",
        releaseYear: 2010,
        releaseOrder: 3,
        chronologicalOrder: 5,
        phaseOrArc: "Faz 1: Avengers Assembled",
        director: "Jon Favreau",
        runtimeMinutes: 124,
        imdbRating: 6.9,
        genres: ["Aksiyon", "Bilim Kurgu"],
        coverUrl: "https://image.tmdb.org/t/p/w500/6WBeq4Mf47nF2QJ4b3Q1a01uNvi.jpg",
        synopsis: "Tony Stark teknolojisini hükümetle paylaşma baskısı ve yeni bir intikamcı düşmanla yüzleşir.",
      },
      {
        id: "mcu-4",
        seriesId: "mcu",
        title: "Thor",
        originalTitle: "Thor",
        releaseYear: 2011,
        releaseOrder: 4,
        chronologicalOrder: 6,
        phaseOrArc: "Faz 1: Avengers Assembled",
        director: "Kenneth Branagh",
        runtimeMinutes: 115,
        imdbRating: 7.0,
        genres: ["Aksiyon", "Fantastik"],
        coverUrl: "https://image.tmdb.org/t/p/w500/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg",
        synopsis: "Kibirli gök gürültüsü tanrısı Thor Dünya'ya sürgün edilir ve layık olmayı öğrenir.",
      },
      {
        id: "mcu-5",
        seriesId: "mcu",
        title: "Captain America: İlk Yenilmez",
        originalTitle: "Captain America: The First Avenger",
        releaseYear: 2011,
        releaseOrder: 5,
        chronologicalOrder: 1,
        phaseOrArc: "Faz 1: Avengers Assembled",
        director: "Joe Johnston",
        runtimeMinutes: 124,
        imdbRating: 6.9,
        genres: ["Aksiyon", "Macera"],
        coverUrl: "https://image.tmdb.org/t/p/w500/vSNxAJTlD0r02V9sPYpqjqD4LJv.jpg",
        synopsis: "2. Dünya Savaşı sırasında Steve Rogers süper asker serumu alarak Kaptan Amerika olur.",
      },
      {
        id: "mcu-6",
        seriesId: "mcu",
        title: "The Avengers",
        originalTitle: "The Avengers",
        releaseYear: 2012,
        releaseOrder: 6,
        chronologicalOrder: 7,
        phaseOrArc: "Faz 1: Avengers Assembled",
        director: "Joss Whedon",
        runtimeMinutes: 143,
        imdbRating: 8.0,
        genres: ["Aksiyon", "Bilim Kurgu"],
        coverUrl: "https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
        synopsis: "Dünya'nın en güçlü kahramanları Loki ve uzaylı ordusuna karşı ilk kez bir araya gelir.",
      },
      // Faz 2
      {
        id: "mcu-7",
        seriesId: "mcu",
        title: "Iron Man 3",
        originalTitle: "Iron Man 3",
        releaseYear: 2013,
        releaseOrder: 7,
        chronologicalOrder: 8,
        phaseOrArc: "Faz 2",
        director: "Shane Black",
        runtimeMinutes: 130,
        imdbRating: 7.1,
        genres: ["Aksiyon", "Bilim Kurgu"],
        coverUrl: "https://image.tmdb.org/t/p/w500/7hxHQ957xMsqa1U1pX7cR29D79F.jpg",
        synopsis: "New York saldırısının travmasını yaşayan Tony, Mandarin adlı gizemli teröriste meydan okur.",
      },
      {
        id: "mcu-8",
        seriesId: "mcu",
        title: "Thor: Karanlık Dünya",
        originalTitle: "Thor: The Dark World",
        releaseYear: 2013,
        releaseOrder: 8,
        chronologicalOrder: 9,
        phaseOrArc: "Faz 2",
        director: "Alan Taylor",
        runtimeMinutes: 112,
        imdbRating: 6.8,
        genres: ["Fantastik", "Aksiyon"],
        coverUrl: "https://image.tmdb.org/t/p/w500/wp6OxE4poJ4G7c0UUh25F0QWdcf.jpg",
        synopsis: "Thor, evreni karanlığa gömmek isteyen Kara Elfler ve Malekith ile savaşır.",
      },
      {
        id: "mcu-9",
        seriesId: "mcu",
        title: "Captain America: Kış Askeri",
        originalTitle: "Captain America: The Winter Soldier",
        releaseYear: 2014,
        releaseOrder: 9,
        chronologicalOrder: 10,
        phaseOrArc: "Faz 2",
        director: "Anthony & Joe Russo",
        runtimeMinutes: 136,
        imdbRating: 7.8,
        genres: ["Aksiyon", "Gerilim"],
        coverUrl: "https://image.tmdb.org/t/p/w500/tVFRMvfN9B78kWJ6x8A2M6PZ0K4.jpg",
        synopsis: "Steve Rogers, S.H.I.E.L.D. içindeki komployu ve geçmişten gelen ölümcül Kış Askeri'ni açığa çıkarır.",
      },
      {
        id: "mcu-10",
        seriesId: "mcu",
        title: "Galaksinin Koruyucuları",
        originalTitle: "Guardians of the Galaxy",
        releaseYear: 2014,
        releaseOrder: 10,
        chronologicalOrder: 11,
        phaseOrArc: "Faz 2",
        director: "James Gunn",
        runtimeMinutes: 121,
        imdbRating: 8.0,
        genres: ["Aksiyon", "Komedi", "Bilim Kurgu"],
        coverUrl: "https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN2Ydgii51I3.jpg",
        synopsis: "Bir grup uyumsuz suçlu, gizemli bir küreyi çalınca galaksiyi kurtarmak zorunda kalır.",
      },
      {
        id: "mcu-11",
        seriesId: "mcu",
        title: "Avengers: Ultron Çağı",
        originalTitle: "Avengers: Age of Ultron",
        releaseYear: 2015,
        releaseOrder: 11,
        chronologicalOrder: 13,
        phaseOrArc: "Faz 2",
        director: "Joss Whedon",
        runtimeMinutes: 141,
        imdbRating: 7.3,
        genres: ["Aksiyon", "Macera"],
        coverUrl: "https://image.tmdb.org/t/p/w500/4ssDuvEDkS9urrpL4ik1LR9DfeP.jpg",
        synopsis: "Tony Stark'ın yapay zeka barış projesi Ultron kontrolden çıkar ve insanlığı yok etmeye kalkışır.",
      },
      {
        id: "mcu-12",
        seriesId: "mcu",
        title: "Ant-Man",
        originalTitle: "Ant-Man",
        releaseYear: 2015,
        releaseOrder: 12,
        chronologicalOrder: 14,
        phaseOrArc: "Faz 2",
        director: "Peyton Reed",
        runtimeMinutes: 117,
        imdbRating: 7.3,
        genres: ["Aksiyon", "Komedi"],
        coverUrl: "https://image.tmdb.org/t/p/w500/8c7q5M0oD16nQn2mU6K6P6d7mP7.jpg",
        synopsis: "Boyut küçültme teknolojisiyle donatılan Scott Lang, dünyayı kurtarmak için soygun yapar.",
      },
      // Faz 3
      {
        id: "mcu-13",
        seriesId: "mcu",
        title: "Captain America: Kahramanların Savaşı",
        originalTitle: "Captain America: Civil War",
        releaseYear: 2016,
        releaseOrder: 13,
        chronologicalOrder: 15,
        phaseOrArc: "Faz 3: Infinity Saga Doruk",
        director: "Anthony & Joe Russo",
        runtimeMinutes: 147,
        imdbRating: 7.8,
        genres: ["Aksiyon", "Bilim Kurgu"],
        coverUrl: "https://image.tmdb.org/t/p/w500/7S9RvfN4e2KzG4d5jK7V8x9Z1d2.jpg",
        synopsis: "Devlet denetimi anlaşmazlığı yüzünden Avengers ekibi Demir Adam ve Kaptan Amerika önderliğinde ikiye bölünür.",
      },
      {
        id: "mcu-14",
        seriesId: "mcu",
        title: "Doctor Strange",
        originalTitle: "Doctor Strange",
        releaseYear: 2016,
        releaseOrder: 14,
        chronologicalOrder: 17,
        phaseOrArc: "Faz 3: Infinity Saga Doruk",
        director: "Scott Derrickson",
        runtimeMinutes: 115,
        imdbRating: 7.5,
        genres: ["Aksiyon", "Fantastik"],
        coverUrl: "https://image.tmdb.org/t/p/w500/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg",
        synopsis: "Kaza geçiren dahi beyin cerrahı Stephen Strange mistik sanatları ve büyü dünyasını keşfeder.",
      },
      {
        id: "mcu-15",
        seriesId: "mcu",
        title: "Galaksinin Koruyucuları 2",
        originalTitle: "Guardians of the Galaxy Vol. 2",
        releaseYear: 2017,
        releaseOrder: 15,
        chronologicalOrder: 12,
        phaseOrArc: "Faz 3: Infinity Saga Doruk",
        director: "James Gunn",
        runtimeMinutes: 136,
        imdbRating: 7.6,
        genres: ["Aksiyon", "Komedi"],
        coverUrl: "https://image.tmdb.org/t/p/w500/y4MBh0EjBlMuOzv9HCZ79vEpvfW.jpg",
        synopsis: "Koruyucular evreni dolaşırken Peter Quill'in gizemli kökenlerini aydınlatır.",
      },
      {
        id: "mcu-16",
        seriesId: "mcu",
        title: "Spider-Man: Eve Dönüş",
        originalTitle: "Spider-Man: Homecoming",
        releaseYear: 2017,
        releaseOrder: 16,
        chronologicalOrder: 16,
        phaseOrArc: "Faz 3: Infinity Saga Doruk",
        director: "Jon Watts",
        runtimeMinutes: 133,
        imdbRating: 7.4,
        genres: ["Aksiyon", "Macera"],
        coverUrl: "https://image.tmdb.org/t/p/w500/c24sv2weTHPsmDa7jEMN0m2P3II.jpg",
        synopsis: "Lise öğrencisi Peter Parker kahramanlık kimliğini oturtmaya çalışırken Akbaba ile savaşır.",
      },
      {
        id: "mcu-17",
        seriesId: "mcu",
        title: "Thor: Ragnarok",
        originalTitle: "Thor: Ragnarok",
        releaseYear: 2017,
        releaseOrder: 17,
        chronologicalOrder: 18,
        phaseOrArc: "Faz 3: Infinity Saga Doruk",
        director: "Taika Waititi",
        runtimeMinutes: 130,
        imdbRating: 7.9,
        genres: ["Aksiyon", "Komedi"],
        coverUrl: "https://image.tmdb.org/t/p/w500/rzRwTcFvttcN1ZpX2xv4jvoY0ND.jpg",
        synopsis: "Hapsedilen Thor, Asgard'ı ölüm tanrıçası Hela'dan kurtarmak için gladyatör arenasında Hulk ile karşılaşır.",
      },
      {
        id: "mcu-18",
        seriesId: "mcu",
        title: "Black Panther",
        originalTitle: "Black Panther",
        releaseYear: 2018,
        releaseOrder: 18,
        chronologicalOrder: 19,
        phaseOrArc: "Faz 3: Infinity Saga Doruk",
        director: "Ryan Coogler",
        runtimeMinutes: 134,
        imdbRating: 7.3,
        genres: ["Aksiyon", "Macera"],
        coverUrl: "https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8vlum.jpg",
        synopsis: "T'Challa, Wakanda tahtına çıkar ancak krallığı tehdit eden eski bir düşmanla yüzleşir.",
      },
      {
        id: "mcu-19",
        seriesId: "mcu",
        title: "Avengers: Sonsuzluk Savaşı",
        originalTitle: "Avengers: Infinity War",
        releaseYear: 2018,
        releaseOrder: 19,
        chronologicalOrder: 20,
        phaseOrArc: "Faz 3: Infinity Saga Doruk",
        director: "Anthony & Joe Russo",
        runtimeMinutes: 149,
        imdbRating: 8.4,
        genres: ["Aksiyon", "Bilim Kurgu"],
        coverUrl: "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
        synopsis: "Avengers ve müttefikleri, evrenin yarısını yok etmek isteyen Thanos'a karşı tüm güçlerini birleştirir.",
      },
      {
        id: "mcu-20",
        seriesId: "mcu",
        title: "Ant-Man and the Wasp",
        originalTitle: "Ant-Man and the Wasp",
        releaseYear: 2018,
        releaseOrder: 20,
        chronologicalOrder: 21,
        phaseOrArc: "Faz 3: Infinity Saga Doruk",
        director: "Peyton Reed",
        runtimeMinutes: 118,
        imdbRating: 7.0,
        genres: ["Aksiyon", "Macera"],
        coverUrl: "https://image.tmdb.org/t/p/w500/eivQmS3wqz9Q1koQ99vK19v7G3S.jpg",
        synopsis: "Scott Lang ve Hope van Dyne Kuantum Alemi'nden Janet'ı kurtarmak için tehlikeli bir göreve çıkar.",
      },
      {
        id: "mcu-21",
        seriesId: "mcu",
        title: "Captain Marvel",
        originalTitle: "Captain Marvel",
        releaseYear: 2019,
        releaseOrder: 21,
        chronologicalOrder: 2,
        phaseOrArc: "Faz 3: Infinity Saga Doruk",
        director: "Anna Boden, Ryan Fleck",
        runtimeMinutes: 124,
        imdbRating: 6.8,
        genres: ["Aksiyon", "Bilim Kurgu"],
        coverUrl: "https://image.tmdb.org/t/p/w500/AtsgWhDnHTq68L0lLNp9Yds40GQ.jpg",
        synopsis: "1995 yılında Carol Danvers galaksiler arası bir savaşta geçmişini ve gerçek güçlerini hatırlar.",
      },
      {
        id: "mcu-22",
        seriesId: "mcu",
        title: "Avengers: Endgame",
        originalTitle: "Avengers: Endgame",
        releaseYear: 2019,
        releaseOrder: 22,
        chronologicalOrder: 22,
        phaseOrArc: "Faz 3: Infinity Saga Doruk",
        director: "Anthony & Joe Russo",
        runtimeMinutes: 181,
        imdbRating: 8.4,
        genres: ["Aksiyon", "Macera"],
        coverUrl: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
        synopsis: "Hayatta kalan kahramanlar zamanda yolculuk yaparak Thanos'un yıkımını geri almaya çalışır.",
      },
      {
        id: "mcu-23",
        seriesId: "mcu",
        title: "Spider-Man: Evden Uzakta",
        originalTitle: "Spider-Man: Far From Home",
        releaseYear: 2019,
        releaseOrder: 23,
        chronologicalOrder: 23,
        phaseOrArc: "Faz 3: Infinity Saga Doruk",
        director: "Jon Watts",
        runtimeMinutes: 129,
        imdbRating: 7.4,
        genres: ["Aksiyon", "Macera"],
        coverUrl: "https://image.tmdb.org/t/p/w500/4q2NNXGjaExGjxAZRuNTL6W27jh.jpg",
        synopsis: "Avrupa okul gezisinde olan Peter Parker, Elementallere karşı Mysterio ile güçlerini birleştirir.",
      },
      // Faz 4 & 5
      {
        id: "mcu-24",
        seriesId: "mcu",
        title: "Black Widow",
        originalTitle: "Black Widow",
        releaseYear: 2021,
        releaseOrder: 24,
        chronologicalOrder: 15,
        phaseOrArc: "Faz 4: Çoklu Evren Başlangıcı",
        director: "Cate Shortland",
        runtimeMinutes: 134,
        imdbRating: 6.7,
        genres: ["Aksiyon", "Gerilim"],
        coverUrl: "https://image.tmdb.org/t/p/w500/qAZ0wh207AmA0q6f9yFwX7UvjW6.jpg",
        synopsis: "Natasha Romanoff geçmişindeki karanlık Kırmızı Oda komplosuyla yüzleşir.",
      },
      {
        id: "mcu-25",
        seriesId: "mcu",
        title: "Spider-Man: Eve Dönüş Yok",
        originalTitle: "Spider-Man: No Way Home",
        releaseYear: 2021,
        releaseOrder: 25,
        chronologicalOrder: 25,
        phaseOrArc: "Faz 4: Çoklu Evren Başlangıcı",
        director: "Jon Watts",
        runtimeMinutes: 148,
        imdbRating: 8.2,
        genres: ["Aksiyon", "Bilim Kurgu"],
        coverUrl: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
        synopsis: "Kimliği açığa çıkan Peter'ın büyüsü çoklu evrenin efsanevi düşmanlarını ve müttefiklerini çeker.",
      },
      {
        id: "mcu-26",
        seriesId: "mcu",
        title: "Doctor Strange: Çoklu Evren Çılgınlığında",
        originalTitle: "Doctor Strange in the Multiverse of Madness",
        releaseYear: 2022,
        releaseOrder: 26,
        chronologicalOrder: 26,
        phaseOrArc: "Faz 4: Çoklu Evren Başlangıcı",
        director: "Sam Raimi",
        runtimeMinutes: 126,
        imdbRating: 6.9,
        genres: ["Aksiyon", "Fantastik"],
        coverUrl: "https://image.tmdb.org/t/p/w500/9Gtg2DzBhmYamXBS1oKAhiwbBKS.jpg",
        synopsis: "Strange çoklu evrenleri aşarak gizemli ve tehlikeli alternatif gerçekliklerle yüzleşir.",
      },
      {
        id: "mcu-27",
        seriesId: "mcu",
        title: "Guardians of the Galaxy Vol. 3",
        originalTitle: "Guardians of the Galaxy Vol. 3",
        releaseYear: 2023,
        releaseOrder: 27,
        chronologicalOrder: 29,
        phaseOrArc: "Faz 5",
        director: "James Gunn",
        runtimeMinutes: 150,
        imdbRating: 7.9,
        genres: ["Aksiyon", "Macera", "Duygusal"],
        coverUrl: "https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN2Ydgii51I3.jpg",
        synopsis: "Rocket'ın hayatını kurtarmak için Koruyucular son ve en dokunaklı yolculuklarına çıkar.",
      },
      {
        id: "mcu-28",
        seriesId: "mcu",
        title: "Deadpool & Wolverine",
        originalTitle: "Deadpool & Wolverine",
        releaseYear: 2024,
        releaseOrder: 28,
        chronologicalOrder: 30,
        phaseOrArc: "Faz 5",
        director: "Shawn Levy",
        runtimeMinutes: 128,
        imdbRating: 7.8,
        genres: ["Aksiyon", "Komedi"],
        coverUrl: "https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
        synopsis: "Wade Wilson evrenini kurtarmak için isteksiz bir Wolverine ile ikonik bir takım kurar.",
      },
    ],
  },
  {
    id: "matrix",
    title: "The Matrix Serisi",
    originalTitle: "The Matrix Collection",
    description:
      "Gerçeklik, simülasyon ve yapay zeka üzerine Wachowski kardeşlerin sinema tarihini değiştiren kült siberpunk serisi.",
    bannerUrl:
      "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80",
    totalMovies: 4,
    averageRating: 7.1,
    genres: ["Bilim Kurgu", "Aksiyon", "Felsefi", "Siberpunk"],
    hasChronologicalOrder: false,
    items: [
      {
        id: "matrix-1",
        seriesId: "matrix",
        title: "The Matrix",
        originalTitle: "The Matrix",
        releaseYear: 1999,
        releaseOrder: 1,
        chronologicalOrder: 1,
        phaseOrArc: "Orijinal Başyapıt",
        director: "Lana & Lilly Wachowski",
        runtimeMinutes: 136,
        imdbRating: 8.7,
        genres: ["Bilim Kurgu", "Aksiyon"],
        coverUrl: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
        synopsis: "Bir bilgisayar korsanı, yaşadığı dünyanın aslında makineler tarafından kontrol edilen yapay bir simülasyon olduğunu keşfeder.",
      },
      {
        id: "matrix-2",
        seriesId: "matrix",
        title: "The Matrix Reloaded",
        originalTitle: "The Matrix Reloaded",
        releaseYear: 2003,
        releaseOrder: 2,
        chronologicalOrder: 2,
        phaseOrArc: "Zion Direnişi",
        director: "Lana & Lilly Wachowski",
        runtimeMinutes: 138,
        imdbRating: 7.2,
        genres: ["Bilim Kurgu", "Aksiyon"],
        coverUrl: "https://image.tmdb.org/t/p/w500/9TGHDvWrqKBzwDxDodHYXEmOE6J.jpg",
        synopsis: "Neo, Trinity ve Morpheus, Zion'u makinelerin ordusundan kurtarmak ve Kaynak'a ulaşmak için savaşır.",
      },
      {
        id: "matrix-3",
        seriesId: "matrix",
        title: "The Matrix Revolutions",
        originalTitle: "The Matrix Revolutions",
        releaseYear: 2003,
        releaseOrder: 3,
        chronologicalOrder: 3,
        phaseOrArc: "Zion Direnişi",
        director: "Lana & Lilly Wachowski",
        runtimeMinutes: 129,
        imdbRating: 6.8,
        genres: ["Bilim Kurgu", "Aksiyon"],
        coverUrl: "https://image.tmdb.org/t/p/w500/fgm8OZ7o4G1G1NBva94Ub7304sr.jpg",
        synopsis: "İnsanlar ve makineler arasındaki savaş son noktasına ulaşırken Neo çıldıran Smith ile son kez kapışır.",
      },
      {
        id: "matrix-4",
        seriesId: "matrix",
        title: "The Matrix Resurrections",
        originalTitle: "The Matrix Resurrections",
        releaseYear: 2021,
        releaseOrder: 4,
        chronologicalOrder: 4,
        phaseOrArc: "Uyanış",
        director: "Lana Wachowski",
        runtimeMinutes: 148,
        imdbRating: 5.7,
        genres: ["Bilim Kurgu", "Aksiyon"],
        coverUrl: "https://image.tmdb.org/t/p/w500/8c4a8kE7PizaGQQvMiMmSuFm314.jpg",
        synopsis: "Thomas Anderson yine tanıdık ama farklılaşmış bir simülasyonun içinde Trinity'yi bulmaya çalışır.",
      },
    ],
  },
  {
    id: "lotr",
    title: "Yüzüklerin Efendisi & Orta Dünya",
    originalTitle: "The Lord of the Rings & The Hobbit",
    description:
      "J.R.R. Tolkien'in ölümsüz evreninden Peter Jackson imzalı 17 Oscar ödüllü destansı Orta Dünya sinema yolculuğu.",
    bannerUrl:
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    totalMovies: 6,
    averageRating: 8.4,
    genres: ["Fantastik", "Macera", "Savaş", "Dram"],
    hasChronologicalOrder: true,
    items: [
      {
        id: "lotr-1",
        seriesId: "lotr",
        title: "The Hobbit: Beklenmedik Yolculuk",
        originalTitle: "The Hobbit: An Unexpected Journey",
        releaseYear: 2012,
        releaseOrder: 4,
        chronologicalOrder: 1,
        phaseOrArc: "Hobbit Üçlemesi (Öncesi)",
        director: "Peter Jackson",
        runtimeMinutes: 169,
        imdbRating: 7.8,
        genres: ["Fantastik", "Macera"],
        coverUrl: "https://image.tmdb.org/t/p/w500/yHA9Fc37VmpUA5IfcPUo9t9Mk43.jpg",
        synopsis: "Bilbo Baggins, Gandalf ve 13 cüce ile birlikte Yalnız Dağ'ı Smaug'dan geri almak için yola koyulur.",
      },
      {
        id: "lotr-2",
        seriesId: "lotr",
        title: "The Hobbit: Smaug'un Çorak Toprakları",
        originalTitle: "The Hobbit: The Desolation of Smaug",
        releaseYear: 2013,
        releaseOrder: 5,
        chronologicalOrder: 2,
        phaseOrArc: "Hobbit Üçlemesi (Öncesi)",
        director: "Peter Jackson",
        runtimeMinutes: 161,
        imdbRating: 7.8,
        genres: ["Fantastik", "Macera"],
        coverUrl: "https://image.tmdb.org/t/p/w500/1X6G51s7VpS2YF5sYwZq1k5p5G.jpg",
        synopsis: "Grup Kuyutorman'dan geçerek göl kasabasına ve nihayet ejderha Smaug'un inine varır.",
      },
      {
        id: "lotr-3",
        seriesId: "lotr",
        title: "The Hobbit: Beş Ordunun Savaşı",
        originalTitle: "The Hobbit: The Battle of the Five Armies",
        releaseYear: 2014,
        releaseOrder: 6,
        chronologicalOrder: 3,
        phaseOrArc: "Hobbit Üçlemesi (Öncesi)",
        director: "Peter Jackson",
        runtimeMinutes: 144,
        imdbRating: 7.4,
        genres: ["Fantastik", "Savaş"],
        coverUrl: "https://image.tmdb.org/t/p/w500/xT98tLqatZPQApyRml42QTCUtZe.jpg",
        synopsis: "Hazine ve toprak için cüceler, elfler, insanlar ve orklar devasa bir meydan savaşına girer.",
      },
      {
        id: "lotr-4",
        seriesId: "lotr",
        title: "Yüzüklerin Efendisi: Yüzük Kardeşliği",
        originalTitle: "The Lord of the Rings: The Fellowship of the Ring",
        releaseYear: 2001,
        releaseOrder: 1,
        chronologicalOrder: 4,
        phaseOrArc: "Yüzüklerin Efendisi Üçlemesi",
        director: "Peter Jackson",
        runtimeMinutes: 178,
        imdbRating: 8.9,
        genres: ["Fantastik", "Macera"],
        coverUrl: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cDK6.jpg",
        synopsis: "Genç Hobbit Frodo, Tek Yüzük'ü Hüküm Dağı'nda yok etmek üzere efsanevi bir kardeşlikle yola çıkar.",
      },
      {
        id: "lotr-5",
        seriesId: "lotr",
        title: "Yüzüklerin Efendisi: İki Kule",
        originalTitle: "The Lord of the Rings: The Two Towers",
        releaseYear: 2002,
        releaseOrder: 2,
        chronologicalOrder: 5,
        phaseOrArc: "Yüzüklerin Efendisi Üçlemesi",
        director: "Peter Jackson",
        runtimeMinutes: 179,
        imdbRating: 8.8,
        genres: ["Fantastik", "Macera"],
        coverUrl: "https://image.tmdb.org/t/p/w500/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
        synopsis: "Kardeşlik dağılır, Miğfer Dibi kuşatması başlar ve Frodo Gollum'un rehberliğinde Mordor'a ilerler.",
      },
      {
        id: "lotr-6",
        seriesId: "lotr",
        title: "Yüzüklerin Efendisi: Kralın Dönüşü",
        originalTitle: "The Lord of the Rings: The Return of the King",
        releaseYear: 2003,
        releaseOrder: 3,
        chronologicalOrder: 6,
        phaseOrArc: "Yüzüklerin Efendisi Üçlemesi",
        director: "Peter Jackson",
        runtimeMinutes: 201,
        imdbRating: 9.0,
        genres: ["Fantastik", "Macera", "Savaş"],
        coverUrl: "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
        synopsis: "Gondor'un kaderi Minas Tirith'te belirlenirken Aragorn krallığına sahip çıkar ve Frodo zirveye varır.",
      },
    ],
  },
  {
    id: "dark-knight",
    title: "Kara Şövalye Üçlemesi (Nolan Batman)",
    originalTitle: "The Dark Knight Trilogy",
    description:
      "Christopher Nolan ve Christian Bale imzalı, çizgi roman sinemacılığının zirvesi kabul edilen efsane üçleme.",
    bannerUrl:
      "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80",
    totalMovies: 3,
    averageRating: 8.5,
    genres: ["Aksiyon", "Suç", "Dram", "Gerilim"],
    hasChronologicalOrder: false,
    items: [
      {
        id: "batman-1",
        seriesId: "dark-knight",
        title: "Batman Başlıyor",
        originalTitle: "Batman Begins",
        releaseYear: 2005,
        releaseOrder: 1,
        chronologicalOrder: 1,
        director: "Christopher Nolan",
        runtimeMinutes: 140,
        imdbRating: 8.2,
        genres: ["Aksiyon", "Suç"],
        coverUrl: "https://image.tmdb.org/t/p/w500/1P3QtW1IkivqPSL7uvEyuhNXJJW.jpg",
        synopsis: "Bruce Wayne gölgeler liginde eğitim alarak Gotham'ın suçlularına korku salan Batman'e dönüşür.",
      },
      {
        id: "batman-2",
        seriesId: "dark-knight",
        title: "Kara Şövalye",
        originalTitle: "The Dark Knight",
        releaseYear: 2008,
        releaseOrder: 2,
        chronologicalOrder: 2,
        director: "Christopher Nolan",
        runtimeMinutes: 152,
        imdbRating: 9.0,
        genres: ["Aksiyon", "Suç", "Dram"],
        coverUrl: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        synopsis: "Batman, Teğmen Gordon ve Harvey Dent üçlüsü Joker'in anarşik kaosuyla en büyük sınavını verir.",
      },
      {
        id: "batman-3",
        seriesId: "dark-knight",
        title: "Kara Şövalye Yükseliyor",
        originalTitle: "The Dark Knight Rises",
        releaseYear: 2012,
        releaseOrder: 3,
        chronologicalOrder: 3,
        director: "Christopher Nolan",
        runtimeMinutes: 165,
        imdbRating: 8.4,
        genres: ["Aksiyon", "Gerilim"],
        coverUrl: "https://image.tmdb.org/t/p/w500/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg",
        synopsis: "Sekiz yıl sonra Gotham, maskeli terörist Bane'in kuşatması altındayken Batman karanlıktan yükselir.",
      },
    ],
  },
  {
    id: "star-wars",
    title: "Star Wars Efsanesi (Skywalker Saga)",
    originalTitle: "Star Wars: The Skywalker Saga",
    description:
      "Gücün aydınlık ve karanlık tarafları, Jedilar ve Sithler arasındaki galaksiyi sarsan 9 bölümlük efsane.",
    bannerUrl:
      "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
    totalMovies: 10,
    averageRating: 7.7,
    genres: ["Bilim Kurgu", "Macera", "Fantastik"],
    hasChronologicalOrder: true,
    items: [
      {
        id: "sw-1",
        seriesId: "star-wars",
        title: "Bölüm I: Gizli Tehlike",
        originalTitle: "Star Wars: Episode I - The Phantom Menace",
        releaseYear: 1999,
        releaseOrder: 4,
        chronologicalOrder: 1,
        phaseOrArc: "Prequel Üçlemesi",
        director: "George Lucas",
        runtimeMinutes: 136,
        imdbRating: 6.5,
        genres: ["Bilim Kurgu", "Macera"],
        coverUrl: "https://image.tmdb.org/t/p/w500/6flBoA0K1v5uW4X04q8cEwU96K.jpg",
        synopsis: "Jedi Şövalyeleri genç Anakin Skywalker'ı keşfeder ve gizli Sith tehlikesi ortaya çıkar.",
      },
      {
        id: "sw-2",
        seriesId: "star-wars",
        title: "Bölüm II: Klonların Saldırısı",
        originalTitle: "Star Wars: Episode II - Attack of the Clones",
        releaseYear: 2002,
        releaseOrder: 5,
        chronologicalOrder: 2,
        phaseOrArc: "Prequel Üçlemesi",
        director: "George Lucas",
        runtimeMinutes: 142,
        imdbRating: 6.6,
        genres: ["Bilim Kurgu", "Macera"],
        coverUrl: "https://image.tmdb.org/t/p/w500/279T255zbf7a4i1A5Ew6QY7l8Pq.jpg",
        synopsis: "Anakin Padmé ile yakınlaşırken Klon Savaşları patlak verir.",
      },
      {
        id: "sw-3",
        seriesId: "star-wars",
        title: "Bölüm III: Sith'in İntikamı",
        originalTitle: "Star Wars: Episode III - Revenge of the Sith",
        releaseYear: 2005,
        releaseOrder: 6,
        chronologicalOrder: 3,
        phaseOrArc: "Prequel Üçlemesi",
        director: "George Lucas",
        runtimeMinutes: 140,
        imdbRating: 7.6,
        genres: ["Bilim Kurgu", "Aksiyon"],
        coverUrl: "https://image.tmdb.org/t/p/w500/xfSAoBVPxtk60FI0wAt85wVq4Ac.jpg",
        synopsis: "Anakin Skywalker karanlık tarafa geçer ve Darth Vader doğar; Cumhuriyet yıkılır.",
      },
      {
        id: "sw-rogue",
        seriesId: "star-wars",
        title: "Rogue One: Bir Star Wars Hikayesi",
        originalTitle: "Rogue One: A Star Wars Story",
        releaseYear: 2016,
        releaseOrder: 8,
        chronologicalOrder: 4,
        phaseOrArc: "Köprü Hikaye",
        director: "Gareth Edwards",
        runtimeMinutes: 133,
        imdbRating: 7.8,
        genres: ["Aksiyon", "Savaş", "Bilim Kurgu"],
        coverUrl: "https://image.tmdb.org/t/p/w500/qjiskwlV1cmFuUXeDFiO6v4vmv9.jpg",
        synopsis: "Bir grup asi savaşçı, Ölüm Yıldızı'nın planlarını çalmak için imkansız bir göreve atılır.",
      },
      {
        id: "sw-4",
        seriesId: "star-wars",
        title: "Bölüm IV: Yeni Bir Umut",
        originalTitle: "Star Wars: Episode IV - A New Hope",
        releaseYear: 1977,
        releaseOrder: 1,
        chronologicalOrder: 5,
        phaseOrArc: "Orijinal Üçleme",
        director: "George Lucas",
        runtimeMinutes: 121,
        imdbRating: 8.6,
        genres: ["Bilim Kurgu", "Macera"],
        coverUrl: "https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
        synopsis: "Luke Skywalker, Han Solo ve Prenses Leia İmparatorluğun ölüm silahını yok etmek için birleşir.",
      },
      {
        id: "sw-5",
        seriesId: "star-wars",
        title: "Bölüm V: İmparator",
        originalTitle: "Star Wars: Episode V - The Empire Strikes Back",
        releaseYear: 1980,
        releaseOrder: 2,
        chronologicalOrder: 6,
        phaseOrArc: "Orijinal Üçleme",
        director: "Irvin Kershner",
        runtimeMinutes: 124,
        imdbRating: 8.7,
        genres: ["Bilim Kurgu", "Macera"],
        coverUrl: "https://image.tmdb.org/t/p/w500/2l05cFUJrqRIFiAnOPpkG1p8zNf.jpg",
        synopsis: "Darth Vader asileri kovalar, Luke Yoda'dan eğitim alır ve şok edici gerçeği öğrenir.",
      },
      {
        id: "sw-6",
        seriesId: "star-wars",
        title: "Bölüm VI: Jedi'ın Dönüşü",
        originalTitle: "Star Wars: Episode VI - Return of the Jedi",
        releaseYear: 1983,
        releaseOrder: 3,
        chronologicalOrder: 7,
        phaseOrArc: "Orijinal Üçleme",
        director: "Richard Marquand",
        runtimeMinutes: 131,
        imdbRating: 8.3,
        genres: ["Bilim Kurgu", "Macera"],
        coverUrl: "https://image.tmdb.org/t/p/w500/xxcn364K4rT04qjM9g8B46fB72D.jpg",
        synopsis: "Galaktik İmparatorluk son savaşını verirken Luke babasının içindeki aydınlığı kurtarmaya çalışır.",
      },
      {
        id: "sw-7",
        seriesId: "star-wars",
        title: "Bölüm VII: Güç Uyanıyor",
        originalTitle: "Star Wars: Episode VII - The Force Awakens",
        releaseYear: 2015,
        releaseOrder: 7,
        chronologicalOrder: 8,
        phaseOrArc: "Devam Üçlemesi",
        director: "J.J. Abrams",
        runtimeMinutes: 138,
        imdbRating: 7.8,
        genres: ["Bilim Kurgu", "Aksiyon"],
        coverUrl: "https://image.tmdb.org/t/p/w500/wqnLen9t85RwhDrk0jL9374092E.jpg",
        synopsis: "Yeni nesil kahramanlar Rey ve Finn, İlk Düzen'e karşı Luke Skywalker'ın izini arar.",
      },
      {
        id: "sw-8",
        seriesId: "star-wars",
        title: "Bölüm VIII: Son Jedi",
        originalTitle: "Star Wars: Episode VIII - The Last Jedi",
        releaseYear: 2017,
        releaseOrder: 9,
        chronologicalOrder: 9,
        phaseOrArc: "Devam Üçlemesi",
        director: "Rian Johnson",
        runtimeMinutes: 152,
        imdbRating: 6.9,
        genres: ["Bilim Kurgu", "Aksiyon"],
        coverUrl: "https://image.tmdb.org/t/p/w500/kOVEVeg59E0wsnXmF9nBYW2YrY.jpg",
        synopsis: "Rey izole durumdaki Luke'tan eğitim almaya çalışırken Direniş yok olmanın eşiğindedir.",
      },
      {
        id: "sw-9",
        seriesId: "star-wars",
        title: "Bölüm IX: Skywalker'ın Yükselişi",
        originalTitle: "Star Wars: Episode IX - The Rise of Skywalker",
        releaseYear: 2019,
        releaseOrder: 10,
        chronologicalOrder: 10,
        phaseOrArc: "Devam Üçlemesi",
        director: "J.J. Abrams",
        runtimeMinutes: 142,
        imdbRating: 6.4,
        genres: ["Bilim Kurgu", "Macera"],
        coverUrl: "https://image.tmdb.org/t/p/w500/db32LaOysVxE9vu9vzOdnSCQG2b.jpg",
        synopsis: "Kadim İmparator'un dönüşüyle birlikte Rey ve Kylo Ren son bir kader savaşında buluşur.",
      },
    ],
  },
  {
    id: "harry-potter",
    title: "Harry Potter & Büyücülük Dünyası",
    originalTitle: "Harry Potter Collection",
    description:
      "Hogwarts Cadılık ve Büyücülük Okulu'nda 'Sağ Kalan Çocuk' Harry Potter ve dostlarının Voldemort'a karşı 8 filmlik destanı.",
    bannerUrl:
      "https://images.unsplash.com/photo-1547756536-cde3673fa2e5?auto=format&fit=crop&w=1200&q=80",
    totalMovies: 8,
    averageRating: 7.7,
    genres: ["Fantastik", "Macera", "Aile"],
    hasChronologicalOrder: false,
    items: [
      {
        id: "hp-1",
        seriesId: "harry-potter",
        title: "Harry Potter ve Felsefe Taşı",
        originalTitle: "Harry Potter and the Sorcerer's Stone",
        releaseYear: 2001,
        releaseOrder: 1,
        chronologicalOrder: 1,
        director: "Chris Columbus",
        runtimeMinutes: 152,
        imdbRating: 7.6,
        genres: ["Fantastik", "Macera"],
        coverUrl: "https://image.tmdb.org/t/p/w500/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
        synopsis: "Yetim Harry 11. yaş gününde bir büyücü olduğunu öğrenir ve Hogwarts'a adım atar.",
      },
      {
        id: "hp-2",
        seriesId: "harry-potter",
        title: "Harry Potter ve Sırlar Odası",
        originalTitle: "Harry Potter and the Chamber of Secrets",
        releaseYear: 2002,
        releaseOrder: 2,
        chronologicalOrder: 2,
        director: "Chris Columbus",
        runtimeMinutes: 161,
        imdbRating: 7.4,
        genres: ["Fantastik", "Gizem"],
        coverUrl: "https://image.tmdb.org/t/p/w500/sdEOH0992YZ02ioWT5AF8Mls0NL.jpg",
        synopsis: "Hogwarts'ta öğrenciler taşa dönüşürken kadim Sırlar Odası yeniden açılır.",
      },
      {
        id: "hp-3",
        seriesId: "harry-potter",
        title: "Harry Potter ve Azkaban Tutsağı",
        originalTitle: "Harry Potter and the Prisoner of Azkaban",
        releaseYear: 2004,
        releaseOrder: 3,
        chronologicalOrder: 3,
        director: "Alfonso Cuarón",
        runtimeMinutes: 142,
        imdbRating: 7.9,
        genres: ["Fantastik", "Gizem"],
        coverUrl: "https://image.tmdb.org/t/p/w500/aWxHgWmb7wUvi5b8bFmsFhDqjR9.jpg",
        synopsis: "Firari mahkum Sirius Black'in peşinde olduğu Harry, geçmişinin karanlık sırlarıyla yüzleşir.",
      },
      {
        id: "hp-4",
        seriesId: "harry-potter",
        title: "Harry Potter ve Ateş Kadehi",
        originalTitle: "Harry Potter and the Goblet of Fire",
        releaseYear: 2005,
        releaseOrder: 4,
        chronologicalOrder: 4,
        director: "Mike Newell",
        runtimeMinutes: 157,
        imdbRating: 7.7,
        genres: ["Fantastik", "Macera"],
        coverUrl: "https://image.tmdb.org/t/p/w500/fECBtHlr0iIQw0W5EQ5LhR2Nxq5.jpg",
        synopsis: "Harry gizemli şekilde Üçbüyücü Turnuvası'na seçilir ve karanlık lord yeniden beden bulur.",
      },
      {
        id: "hp-5",
        seriesId: "harry-potter",
        title: "Harry Potter ve Zümrüdüanka Yoldaşlığı",
        originalTitle: "Harry Potter and the Order of the Phoenix",
        releaseYear: 2007,
        releaseOrder: 5,
        chronologicalOrder: 5,
        director: "David Yates",
        runtimeMinutes: 138,
        imdbRating: 7.5,
        genres: ["Fantastik", "Dram"],
        coverUrl: "https://image.tmdb.org/t/p/w500/5aGhaI2f4v26k5o7h9a7V144x9P.jpg",
        synopsis: "Bakanlığın inkarına karşı Harry Dumbledore'un Ordusu'nu gizlice eğitir.",
      },
      {
        id: "hp-6",
        seriesId: "harry-potter",
        title: "Harry Potter ve Melez Prens",
        originalTitle: "Harry Potter and the Half-Blood Prince",
        releaseYear: 2009,
        releaseOrder: 6,
        chronologicalOrder: 6,
        director: "David Yates",
        runtimeMinutes: 153,
        imdbRating: 7.6,
        genres: ["Fantastik", "Macera"],
        coverUrl: "https://image.tmdb.org/t/p/w500/z7uo9zmQdQwZs25O1v9U7wW4qG.jpg",
        synopsis: "Dumbledore Harry'yi Voldemort'un Hortkuluklarını keşfetmek için hazırlar.",
      },
      {
        id: "hp-7",
        seriesId: "harry-potter",
        title: "Harry Potter ve Ölüm Yadigarları: Bölüm 1",
        originalTitle: "Harry Potter and the Deathly Hallows: Part 1",
        releaseYear: 2010,
        releaseOrder: 7,
        chronologicalOrder: 7,
        director: "David Yates",
        runtimeMinutes: 146,
        imdbRating: 7.7,
        genres: ["Fantastik", "Macera"],
        coverUrl: "https://image.tmdb.org/t/p/w500/iGoXIpQb7Pot00GQ9vF19uwwkG.jpg",
        synopsis: "Harry, Ron ve Hermione Hogwarts'ı bırakarak Hortkulukları bulmak için tehlikeli bir kaçışa başlar.",
      },
      {
        id: "hp-8",
        seriesId: "harry-potter",
        title: "Harry Potter ve Ölüm Yadigarları: Bölüm 2",
        originalTitle: "Harry Potter and the Deathly Hallows: Part 2",
        releaseYear: 2011,
        releaseOrder: 8,
        chronologicalOrder: 8,
        director: "David Yates",
        runtimeMinutes: 130,
        imdbRating: 8.1,
        genres: ["Fantastik", "Aksiyon", "Macera"],
        coverUrl: "https://image.tmdb.org/t/p/w500/c54HpQmuwXj0gq9VGzgraNayj0f.jpg",
        synopsis: "Hogwarts Savaşı patlak verir ve Harry ile Voldemort arasındaki nihai yüzleşme gerçekleşir.",
      },
    ],
  },
  {
    id: "john-wick",
    title: "John Wick Serisi",
    originalTitle: "John Wick Collection",
    description:
      "Keanu Reeves'in hayat verdiği efsanevi suikastçı Baba Yaga'nın High Table'a karşı durdurulamaz intikam ve hayatta kalma savaşı.",
    bannerUrl:
      "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80",
    totalMovies: 4,
    averageRating: 7.5,
    genres: ["Aksiyon", "Gerilim", "Suç", "Gun-Fu"],
    hasChronologicalOrder: false,
    items: [
      {
        id: "jw-1",
        seriesId: "john-wick",
        title: "John Wick",
        originalTitle: "John Wick",
        releaseYear: 2014,
        releaseOrder: 1,
        chronologicalOrder: 1,
        director: "Chad Stahelski",
        runtimeMinutes: 101,
        imdbRating: 7.4,
        genres: ["Aksiyon", "Gerilim"],
        coverUrl: "https://image.tmdb.org/t/p/w500/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg",
        synopsis: "Emekli suikastçı, ölen karısının hediyesi köpeğini öldüren gangsterlerden intikam almak için geri döner.",
      },
      {
        id: "jw-2",
        seriesId: "john-wick",
        title: "John Wick: Bölüm 2",
        originalTitle: "John Wick: Chapter 2",
        releaseYear: 2017,
        releaseOrder: 2,
        chronologicalOrder: 2,
        director: "Chad Stahelski",
        runtimeMinutes: 122,
        imdbRating: 7.4,
        genres: ["Aksiyon", "Suç"],
        coverUrl: "https://image.tmdb.org/t/p/w500/kZJSkG1q1F1q2c8w3G4c6y7JkP.jpg",
        synopsis: "Eski bir kan yemini nedeniyle John Wick Roma'daki suç lordlarına karşı imkansız bir suikast görevi üstlenir.",
      },
      {
        id: "jw-3",
        seriesId: "john-wick",
        title: "John Wick: Bölüm 3 - Parabellum",
        originalTitle: "John Wick: Chapter 3 - Parabellum",
        releaseYear: 2019,
        releaseOrder: 3,
        chronologicalOrder: 3,
        director: "Chad Stahelski",
        runtimeMinutes: 130,
        imdbRating: 7.4,
        genres: ["Aksiyon", "Gerilim"],
        coverUrl: "https://image.tmdb.org/t/p/w500/ziEuG1essDuWuC5lpWUaw1uXY2O.jpg",
        synopsis: "Başına 14 milyon dolarlık ödül konan ve aforoz edilen John Wick New York'tan kaçmak için savaşır.",
      },
      {
        id: "jw-4",
        seriesId: "john-wick",
        title: "John Wick: Bölüm 4",
        originalTitle: "John Wick: Chapter 4",
        releaseYear: 2023,
        releaseOrder: 4,
        chronologicalOrder: 4,
        director: "Chad Stahelski",
        runtimeMinutes: 169,
        imdbRating: 7.7,
        genres: ["Aksiyon", "Gerilim"],
        coverUrl: "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
        synopsis: "Wick, High Table'ı yenmenin ve özgürlüğünü geri kazanmanın tek yolunu Paris'te arar.",
      },
    ],
  },
  {
    id: "mission-impossible",
    title: "Görevimiz Tehlike (Mission: Impossible)",
    originalTitle: "Mission: Impossible Collection",
    description:
      "Tom Cruise'un dublörsüz nefes kesen akrobasi sahneleriyle Ethan Hunt ve IMF ekibinin dünyayı kurtaran operasyonları.",
    bannerUrl:
      "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1200&q=80",
    totalMovies: 7,
    averageRating: 7.3,
    genres: ["Aksiyon", "Casusluk", "Gerilim"],
    hasChronologicalOrder: false,
    items: [
      {
        id: "mi-1",
        seriesId: "mission-impossible",
        title: "Görevimiz Tehlike",
        originalTitle: "Mission: Impossible",
        releaseYear: 1996,
        releaseOrder: 1,
        chronologicalOrder: 1,
        director: "Brian De Palma",
        runtimeMinutes: 110,
        imdbRating: 7.2,
        genres: ["Casusluk", "Aksiyon"],
        coverUrl: "https://image.tmdb.org/t/p/w500/lFvj1F5Xg8dG4c0h4Y4sQ.jpg",
        synopsis: "İhanete uğrayan ajan Ethan Hunt köstebeği bulup adını temize çıkarmak için CIA'ye sızar.",
      },
      {
        id: "mi-4",
        seriesId: "mission-impossible",
        title: "Görevimiz Tehlike: Hayalet Protokol",
        originalTitle: "Mission: Impossible - Ghost Protocol",
        releaseYear: 2011,
        releaseOrder: 4,
        chronologicalOrder: 4,
        director: "Brad Bird",
        runtimeMinutes: 132,
        imdbRating: 7.4,
        genres: ["Casusluk", "Aksiyon"],
        coverUrl: "https://image.tmdb.org/t/p/w500/s586cwWDbqX519QyE.jpg",
        synopsis: "Kremlin bombalamasının ardından kapatılan IMF adına çalışan Hunt, Burç Halife'ye tırmanır.",
      },
      {
        id: "mi-5",
        seriesId: "mission-impossible",
        title: "Görevimiz Tehlike: Rogue Nation",
        originalTitle: "Mission: Impossible - Rogue Nation",
        releaseYear: 2015,
        releaseOrder: 5,
        chronologicalOrder: 5,
        director: "Christopher McQuarrie",
        runtimeMinutes: 131,
        imdbRating: 7.4,
        genres: ["Casusluk", "Aksiyon"],
        coverUrl: "https://image.tmdb.org/t/p/w500/1QkLwYV9a6B8P.jpg",
        synopsis: "Ethan Hunt hain ajanlardan kurulu Syndicate örgütünü çökertmek için operasyon başlatır.",
      },
      {
        id: "mi-6",
        seriesId: "mission-impossible",
        title: "Görevimiz Tehlike: Yansımalar (Fallout)",
        originalTitle: "Mission: Impossible - Fallout",
        releaseYear: 2018,
        releaseOrder: 6,
        chronologicalOrder: 6,
        director: "Christopher McQuarrie",
        runtimeMinutes: 147,
        imdbRating: 7.7,
        genres: ["Casusluk", "Aksiyon"],
        coverUrl: "https://image.tmdb.org/t/p/w500/AkJQvtR098.jpg",
        synopsis: "Çalınan plütonyumları geri almak isteyen Ethan zamana ve eski düşmanlarına karşı yarışır.",
      },
      {
        id: "mi-7",
        seriesId: "mission-impossible",
        title: "Görevimiz Tehlike: Ölümcül Hesaplaşma Bölüm 1",
        originalTitle: "Mission: Impossible - Dead Reckoning Part One",
        releaseYear: 2023,
        releaseOrder: 7,
        chronologicalOrder: 7,
        director: "Christopher McQuarrie",
        runtimeMinutes: 163,
        imdbRating: 7.7,
        genres: ["Casusluk", "Aksiyon"],
        coverUrl: "https://image.tmdb.org/t/p/w500/NNxYkU70HP.jpg",
        synopsis: "Tüm insanlığı tehdit eden yapay zeka Entity'yi kontrol edecek anahtarı ele geçirme yarışı.",
      },
    ],
  },
  {
    id: "back-to-the-future",
    title: "Geleceğe Dönüş Üçlemesi",
    originalTitle: "Back to the Future Trilogy",
    description:
      "Marty McFly ve Dr. Emmett Brown'ın zaman makinesi DeLorean ile 1955, 2015 ve 1885 yıllarına yaptığı zamansız macera.",
    bannerUrl:
      "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=1200&q=80",
    totalMovies: 3,
    averageRating: 7.9,
    genres: ["Bilim Kurgu", "Komedi", "Macera"],
    hasChronologicalOrder: false,
    items: [
      {
        id: "bttf-1",
        seriesId: "back-to-the-future",
        title: "Geleceğe Dönüş",
        originalTitle: "Back to the Future",
        releaseYear: 1985,
        releaseOrder: 1,
        chronologicalOrder: 1,
        director: "Robert Zemeckis",
        runtimeMinutes: 116,
        imdbRating: 8.5,
        genres: ["Bilim Kurgu", "Komedi"],
        coverUrl: "https://image.tmdb.org/t/p/w500/fNOH9f1aA7X9iG5o9f9.jpg",
        synopsis: "Marty yanlışlıkla 1955'e gider ve geleceğinin silinmemesi için anne babasını aşık etmek zorundadır.",
      },
      {
        id: "bttf-2",
        seriesId: "back-to-the-future",
        title: "Geleceğe Dönüş II",
        originalTitle: "Back to the Future Part II",
        releaseYear: 1989,
        releaseOrder: 2,
        chronologicalOrder: 2,
        director: "Robert Zemeckis",
        runtimeMinutes: 108,
        imdbRating: 7.8,
        genres: ["Bilim Kurgu", "Komedi"],
        coverUrl: "https://image.tmdb.org/t/p/w500/eWcvZ8vD.jpg",
        synopsis: "Gelecekteki çocuklarını kurtarmak için 2015'e giden Marty, alternatif bir 1985 kabusuyla karşılaşır.",
      },
      {
        id: "bttf-3",
        seriesId: "back-to-the-future",
        title: "Geleceğe Dönüş III",
        originalTitle: "Back to the Future Part III",
        releaseYear: 1990,
        releaseOrder: 3,
        chronologicalOrder: 3,
        director: "Robert Zemeckis",
        runtimeMinutes: 118,
        imdbRating: 7.5,
        genres: ["Bilim Kurgu", "Vahşi Batı"],
        coverUrl: "https://image.tmdb.org/t/p/w500/k8a7f.jpg",
        synopsis: "Marty, Doc Brown'ı kurtarmak için 1885 Vahşi Batısı'na seyahat eder.",
      },
    ],
  },
];

/**
 * Normalizes movie titles for reliable matching between series items and user library items.
 */
export function normalizeTitle(title: string): string {
  return title
    .toLowerCase()
    .replace(/^(the|a|an)\s+/i, "")
    .replace(/[^\p{L}\p{N}]/gu, "")
    .trim();
}

/**
 * Returns all curated movie series.
 */
export function getMovieSeriesList(): MovieSeries[] {
  return CURATED_MOVIE_SERIES;
}

/**
 * Finds a specific series by its unique ID.
 */
export function getMovieSeriesById(id: string): MovieSeries | undefined {
  return CURATED_MOVIE_SERIES.find((s) => s.id === id);
}

export interface SeriesItemProgress {
  seriesItem: MovieSeriesItem;
  userItem?: MediaItem;
  status?: "completed" | "backlog" | "in_progress" | "dropped";
  isWatched: boolean;
  isWatchlist: boolean;
  rating?: number;
}

export interface SeriesProgressResult {
  seriesId: string;
  totalMovies: number;
  watchedCount: number;
  watchlistCount: number;
  percent: number;
  nextUpItem?: MovieSeriesItem;
  itemStatuses: SeriesItemProgress[];
}

/**
 * Computes how much of a series the user has watched and matches with user's MediaItems.
 */
export function computeSeriesProgress(
  series: MovieSeries,
  userItems: MediaItem[],
): SeriesProgressResult {
  let watchedCount = 0;
  let watchlistCount = 0;
  let nextUpItem: MovieSeriesItem | undefined = undefined;

  const itemStatuses: SeriesItemProgress[] = series.items.map((movie) => {
    const movieNormTitle = normalizeTitle(movie.title);
    const movieOrigNorm = movie.originalTitle
      ? normalizeTitle(movie.originalTitle)
      : "";

    // Match either by explicit seriesItemId or by title similarity
    const matchedUserItem = userItems.find((u) => {
      if (u.seriesItemId && u.seriesItemId === movie.id) return true;
      if (u.type !== "movie") return false;
      const uNorm = normalizeTitle(u.title);
      return (
        uNorm === movieNormTitle ||
        (movieOrigNorm && uNorm === movieOrigNorm) ||
        (movie.releaseYear &&
          u.releaseYear === movie.releaseYear &&
          (uNorm.includes(movieNormTitle) || movieNormTitle.includes(uNorm)))
      );
    });

    const isWatched = matchedUserItem?.status === "completed";
    const isWatchlist = matchedUserItem?.status === "backlog";

    if (isWatched) {
      watchedCount++;
    } else if (isWatchlist) {
      watchlistCount++;
    } else if (!nextUpItem) {
      nextUpItem = movie;
    }

    return {
      seriesItem: movie,
      userItem: matchedUserItem,
      status: matchedUserItem?.status,
      isWatched,
      isWatchlist,
      rating: matchedUserItem?.rating,
    };
  });

  const total = series.items.length;
  const percent = total > 0 ? Math.round((watchedCount / total) * 100) : 0;

  return {
    seriesId: series.id,
    totalMovies: total,
    watchedCount,
    watchlistCount,
    percent,
    nextUpItem,
    itemStatuses,
  };
}
