/**
 * TurkeyHistoryData.ts
 * KPSS Tarih Haritası — Selçuklu, Beylikler ve Osmanlı Devleti (1299-1922).
 *
 * 3 görüntüleme modu:
 *  - territory: her olay kendi döneminin sınır illerini boyar (birikimli)
 *  - points: nokta + etiket (ekonomi/kültür merkezleri)
 *  - diagram: hiyerarşi şeması (devlet teşkilatı) — SchemaBuilder ile çizilir
 */

export type HistoryMode = "territory" | "points" | "diagram";

export interface HistoryEvent {
  year?: number;
  title: string;
  city?: string;
  desc: string;
  tag?: string;
  /** territory modunda bu olayın boyanacağı iller */
  territory?: string[];
  color?: string;
  x: number;
  y: number;
}

export interface HistoryLegendRow {
  c: string;
  l: string;
}

export interface HistoryUnit {
  id: string;
  navLabel: string;
  mode: HistoryMode;
  title: string;
  subtitle: string;
  showYear: boolean;
  color: string;
  legend: HistoryLegendRow[] | null;
  events?: HistoryEvent[];
}

export const HISTORY_VIEWBOX = "0 0 1000.0 421.9991241865445";

/** Varsayılan il rengi (parşömen) */
export const HISTORY_PROVINCE_FILL = "#d8cba7";
export const HISTORY_PROVINCE_STROKE = "#a3906a";

export const HISTORY_UNITS: HistoryUnit[] = [
  {
    id: "anadolu-selcuklu",
    navLabel: "Anadolu Selçuklu Devleti",
    mode: "territory",
    title: "Anadolu Selçuklu Devleti: Kuruluştan Yıkılışa",
    subtitle: "10 kilit olay · 1071-1308 · sırasıyla oynat",
    showYear: true,
    color: "#1f5f7a",
    legend: [{ c: "#1f5f7a", l: "Anadolu Selçuklu toprağı" }],
    events: [
      {
        year: 1071,
        title: "Malazgirt Zaferi",
        city: "Malazgirt (Muş)",
        desc: "Sultan Alparslan, Bizans ordusunu yendi; Anadolu'nun kapıları Türklere açıldı.",
        tag: "Öncül Olay",
        territory: [],
        x: 880.5,
        y: 198.5,
      },
      {
        year: 1075,
        title: "Anadolu Selçuklu Devleti'nin kuruluşu",
        city: "İznik (Bursa)",
        desc: "Kutalmışoğlu Süleyman Şah, İznik'i başkent yaparak devleti kurdu.",
        tag: "Kuruluş",
        territory: [
          "Bilecik",
          "Bursa",
          "Kocaeli",
          "Sakarya",
          "Yalova",
          "Eskişehir",
        ],
        color: "#1f5f7a",
        x: 211.5,
        y: 112.3,
      },
      {
        year: 1097,
        title: "İznik'in kaybı, başkent Konya'ya taşınıyor",
        city: "Konya",
        desc: "I. Haçlı Seferi sonrası İznik elden çıktı; devlet merkezi Konya'ya taşındı.",
        tag: "Başkent Değişimi",
        territory: [
          "Konya",
          "Karaman",
          "Aksaray",
          "Ankara",
          "Kırşehir",
          "Kırıkkale",
          "Nevşehir",
          "Niğde",
          "Kayseri",
          "Yozgat",
          "Çankırı",
        ],
        color: "#1f5f7a",
        x: 355.7,
        y: 283.9,
      },
      {
        year: 1176,
        title: "Miryokefalon Zaferi",
        city: "Honaz (Denizli)",
        desc: "II. Kılıç Arslan, Bizans'ı ağır bir yenilgiye uğratarak Anadolu'nun Türk yurdu olduğunu kesinleştirdi.",
        tag: "Zafer / Güçlenme",
        territory: ["Denizli", "Uşak", "Afyon", "Kütahya", "Isparta", "Burdur"],
        color: "#1f5f7a",
        x: 178.6,
        y: 290.5,
      },
      {
        year: 1186,
        title: "Ülkenin 11 oğula paylaştırılması",
        city: "Konya",
        desc: "II. Kılıç Arslan ülkeyi oğulları arasında paylaştırdı; taht kavgaları ve iç karışıklık dönemi başladı.",
        tag: "İç Karışıklık",
        territory: [],
        color: "" as string,
        x: 355.7,
        y: 283.9,
      },
      {
        year: 1214,
        title: "Sinop'un fethi",
        city: "Sinop",
        desc: "I. İzzeddin Keykavus, Sinop'u alarak devleti Karadeniz'e açtı.",
        tag: "Fetih",
        territory: ["Sinop", "Kastamonu", "Çorum", "Amasya", "Tokat", "Samsun"],
        color: "#1f5f7a",
        x: 495,
        y: 5.3,
      },
      {
        year: 1221,
        title: "Alanya'nın fethi",
        city: "Alanya (Antalya)",
        desc: "I. Alaeddin Keykubad, Alanya'yı alıp devleti Akdeniz'e açtı; en parlak dönem başladı.",
        tag: "Fetih",
        territory: ["Antalya", "Mersin"],
        color: "#1f5f7a",
        x: 330.4,
        y: 373.1,
      },
      {
        year: 1230,
        title: "Yassıçemen Savaşı",
        city: "Yassıçemen (Erzincan)",
        desc: "Celaleddin Harzemşah'a karşı kazanılan zaferle doğuya genişlendi; ancak Moğollara karşı tampon devlet ortadan kalktı.",
        tag: "Zafer / Genişleme",
        territory: [
          "Erzincan",
          "Sivas",
          "Malatya",
          "Elazığ",
          "Adıyaman",
          "Kahramanmaraş",
        ],
        color: "#1f5f7a",
        x: 682,
        y: 168,
      },
      {
        year: 1243,
        title: "Kösedağ Savaşı",
        city: "Kösedağ (Sivas civarı)",
        desc: "Moğollara ağır bir yenilgi; devlet İlhanlılara bağımlı (vassal) hale geldi, gerileme dönemi başladı.",
        tag: "Gerileme",
        territory: [],
        color: "" as string,
        x: 648.6,
        y: 129.8,
      },
      {
        year: 1308,
        title: "Devletin sona ermesi",
        city: "Konya",
        desc: "Son Selçuklu sultanının ölümüyle devlet fiilen sona erdi; toprakları Anadolu Beyliklerine bölündü.",
        tag: "Yıkılış",
        territory: [],
        color: "" as string,
        x: 355.7,
        y: 283.9,
      },
    ],
  },

  /* ---------------- OSMANLI KURULUŞ DÖNEMİ ---------------- */
  {
    id: "osmanli-kurulus",
    navLabel: "Osmanlı Kuruluş (1299-1453)",
    mode: "territory",
    title: "Osmanlı Devleti Kuruluş Dönemi",
    subtitle: "13 kilit gelişme · Söğüt'ten İstanbul'un Fethine (1299-1453)",
    showYear: true,
    color: "#b91c1c",
    legend: [{ c: "#b91c1c", l: "Osmanlı Kuruluş Toprakları" }],
    events: [
      {
        year: 1299,
        title: "Osmanlı Beyliği'nin Kuruluşu",
        city: "Söğüt (Bilecik)",
        desc: "Osman Bey bağımsızlığını ilan ederek Osmanlı Beyliği'ni kurdu.",
        tag: "Kuruluş",
        territory: ["Bilecik", "Eskişehir"],
        color: "#b91c1c",
        x: 235.3,
        y: 141.4,
      },
      {
        year: 1302,
        title: "Koyunhisar (Bafeus) Savaşı",
        city: "Yalova",
        desc: "Osmanlı ile Bizans arasındaki ilk düzenli meydan savaşı kazanıldı.",
        tag: "Zafer",
        territory: ["Yalova"],
        color: "#b91c1c",
        x: 195.0,
        y: 88.0,
      },
      {
        year: 1326,
        title: "Bursa'nın Fethi ve Başkent Olması",
        city: "Bursa",
        desc: "Orhan Bey Bursa'yı fethederek devlet merkezi yaptı.",
        tag: "Başkent",
        territory: ["Bursa"],
        color: "#b91c1c",
        x: 175.0,
        y: 127.0,
      },
      {
        year: 1329,
        title: "Palekanon (Maltepe) Savaşı",
        city: "Kocaeli",
        desc: "Bizans İmparatoru yenilgiye uğratıldı; İznik'in fethi kolaylaştı.",
        tag: "Zafer",
        territory: ["Kocaeli", "Sakarya"],
        color: "#b91c1c",
        x: 220.0,
        y: 75.0,
      },
      {
        year: 1331,
        title: "İznik'in Fethi & İlk Medrese",
        city: "İznik (Bursa)",
        desc: "İznik fethedildi ve ilk Osmanlı Medresei (İznik Orhaniyesi) açıldı.",
        tag: "Eğitim / Fetih",
        territory: [],
        x: 200.9,
        y: 112.0,
      },
      {
        year: 1345,
        title: "Karesioğulları Beyliği'nin Katılması",
        city: "Balıkesir / Çanakkale",
        desc: "Osmanlı'ya katılan ilk beylik. İlk donanma ve denizcilik faaliyetleri başladı.",
        tag: "İlk Donanma",
        territory: ["Balıkesir", "Çanakkale"],
        color: "#b91c1c",
        x: 117.4,
        y: 168.0,
      },
      {
        year: 1353,
        title: "Çimpe Kalesi'nin Alınması",
        city: "Gelibolu (Çanakkale)",
        desc: "Bizans'a yardım karşılığı alındı; Rumeli'deki ilk Osmanlı toprağı oldu.",
        tag: "Rumeli'ye Geçiş",
        territory: [],
        x: 45.0,
        y: 120.0,
      },
      {
        year: 1361,
        title: "Edirne'nin Fethi ve Başkent Yapılması",
        city: "Edirne",
        desc: "I. Murad Edirne'yi fethederek devlet merkezini Rumeli'ye taşıdı.",
        tag: "Başkent",
        territory: ["Edirne", "Tekirdağ", "Kırklareli"],
        color: "#b91c1c",
        x: 50.0,
        y: 40.0,
      },
      {
        year: 1364,
        title: "Sırpsındığı Zaferi",
        city: "Edirne yakınları",
        desc: "Haçlı ordusuna karşı kazanılan ilk büyük Osmanlı zaferi.",
        tag: "Haçlı Savaşı",
        territory: [],
        x: 60.0,
        y: 45.0,
      },
      {
        year: 1389,
        title: "I. Kosova Savaşı",
        city: "Kosova",
        desc: "Balkanlarda Osmanlı hakimiyeti güçlendi; I. Murad savaş meydanında şehit düştü.",
        tag: "Zafer",
        territory: [],
        x: 20.0,
        y: 30.0,
      },
      {
        year: 1396,
        title: "Niğbolu Savaşı",
        city: "Niğbolu (Bulgaristan)",
        desc: "Yıldırım Bayezid Haçlıları yendi; Abbasi halifesi kendisine 'Sultan-ı İklim-i Rum' unvanı verdi.",
        tag: "Zafer / Unvan",
        territory: [],
        x: 30.0,
        y: 20.0,
      },
      {
        year: 1402,
        title: "Ankara Savaşı & Fetret Devri",
        city: "Ankara (Çubuk)",
        desc: "Timur'a karşı yenilgi; 11 yıl sürecek taht kavgaları ve Fetret Devri başladı.",
        tag: "Fetret Devri",
        territory: [],
        x: 367.9,
        y: 181.3,
      },
      {
        year: 1448,
        title: "II. Kosova Savaşı",
        city: "Kosova",
        desc: "II. Murad Haçlıları bozguna uğrattı; Türklerin Balkanlar'dan atılamayacağı kesinleşti.",
        tag: "Balkan Hakimiyeti",
        territory: [],
        x: 20.0,
        y: 30.0,
      },
    ],
  },

  /* ---------------- OSMANLI YÜKSELME DÖNEMİ ---------------- */
  {
    id: "osmanli-yukselme",
    navLabel: "Osmanlı Yükselme (1453-1579)",
    mode: "territory",
    title: "Osmanlı Devleti Yükselme Dönemi (Klasik Çağ)",
    subtitle: "11 şanlı gelişme · İstanbul'un Fethinden Sokullu'ya (1453-1579)",
    showYear: true,
    color: "#c99a3c",
    legend: [{ c: "#c99a3c", l: "Osmanlı İmparatorluk Toprağı" }],
    events: [
      {
        year: 1453,
        title: "İstanbul'un Fethi",
        city: "İstanbul",
        desc: "Fatih Sultan Mehmet 1100 yıllık Bizans İmparatorluğu'nu yıktı; Orta Çağ kapandı, Yeni Çağ başladı.",
        tag: "Dünya Tarihi Miladı",
        territory: ["İstanbul"],
        color: "#c99a3c",
        x: 190.4,
        y: 69.8,
      },
      {
        year: 1461,
        title: "Trabzon Rum İmparatorluğu'nun Fethi",
        city: "Trabzon",
        desc: "Fatih Trabzon'u alarak Bizans'ı diriltme umutlarını tamamen bitirdi ve Karadeniz kıyısını güvenceye aldı.",
        tag: "Fetih",
        territory: ["Trabzon", "Rize", "Giresun"],
        color: "#c99a3c",
        x: 740.0,
        y: 80.0,
      },
      {
        year: 1473,
        title: "Otlukbeli Savaşı",
        city: "Otlukbeli (Erzincan)",
        desc: "Fatih, Akkoyunlu Hükümdarı Uzun Hasan'ı yenerek Doğu Anadolu hakimiyetini pekiştirdi.",
        tag: "Zafer",
        territory: ["Erzincan", "Erzurum"],
        color: "#c99a3c",
        x: 723.4,
        y: 174.5,
      },
      {
        year: 1475,
        title: "Kırım'ın Fethi",
        city: "Kırım Yarımadası",
        desc: "Gedik Ahmet Paşa Kırım'ı bağladı; Karadeniz tamamen Türk Gölü haline geldi.",
        tag: "Türk Gölü",
        territory: [],
        x: 550.0,
        y: -30.0,
      },
      {
        year: 1514,
        title: "Çaldıran Savaşı",
        city: "Çaldıran (Van)",
        desc: "Yavuz Sultan Selim Safevi Şahı İsmail'i yendi; Doğu Anadolu emniyete alındı.",
        tag: "Zafer",
        territory: ["Van", "Ağrı", "Muş", "Bitlis"],
        color: "#c99a3c",
        x: 920.0,
        y: 200.0,
      },
      {
        year: 1515,
        title: "Turnadağ Savaşı",
        city: "Kahramanmaraş",
        desc: "Dulkadiroğulları Beyliği'ne son verildi; Anadolu Türk siyasi birliği kesin olarak sağlandı.",
        tag: "Türk Birliği",
        territory: ["Kahramanmaraş", "Gaziantep"],
        color: "#c99a3c",
        x: 592.4,
        y: 323.0,
      },
      {
        year: 1517,
        title: "Ridaniye Savaşı & Halifeliğin Geçişi",
        city: "Kahire (Mısır)",
        desc: "Memlük Devleti yıkıldı; Kutsal Emanetler İstanbul'a getirildi, Halifelik Osmanlı'ya geçti.",
        tag: "Halifelik",
        territory: ["Şanlıurfa", "Diyarbakır", "Mardin"],
        color: "#c99a3c",
        x: 739.0,
        y: 322.4,
      },
      {
        year: 1521,
        title: "Belgrat'ın Fethi",
        city: "Belgrat (Sırbistan)",
        desc: "Kanuni Sultan Süleyman Avrupa seferlerinin kapısını açan Belgrat'ı fethetti.",
        tag: "Fetih",
        territory: [],
        x: 20.0,
        y: 10.0,
      },
      {
        year: 1526,
        title: "Mohaç Meydan Muharebesi",
        city: "Mohaç (Macaristan)",
        desc: "2 saat gibi kısa bir sürede Macar ordusu imha edildi; Macaristan Osmanlı'ya bağlandı.",
        tag: "Dünya Rekoru Zafer",
        territory: [],
        x: 10.0,
        y: 5.0,
      },
      {
        year: 1538,
        title: "Preveze Deniz Zaferi",
        city: "Preveze (Yunanistan)",
        desc: "Barbaros Hayreddin Paşa Haçlı donanmasını yok etti; Akdeniz Türk Gölü oldu.",
        tag: "Akdeniz Hakimiyeti",
        territory: [],
        x: 10.0,
        y: 150.0,
      },
      {
        year: 1571,
        title: "Kıbrıs'ın Fethi",
        city: "Kıbrıs Adası",
        desc: "Lala Mustafa Paşa ve Sokullu Mehmet Paşa döneminde Doğu Akdeniz ticaret yolu güvenceye alındı.",
        tag: "Deniz Fethi",
        territory: [],
        x: 420.0,
        y: 410.0,
      },
    ],
  },

  /* ---------------- OSMANLI DURAKLAMA DÖNEMİ ---------------- */
  {
    id: "osmanli-duraklama",
    navLabel: "Osmanlı Duraklama (1579-1699)",
    mode: "territory",
    title: "Osmanlı Devleti Duraklama Dönemi (Arayış Yılları)",
    subtitle: "9 kritik süreç · Ferhat Paşa'dan Karlofça'ya (1579-1699)",
    showYear: true,
    color: "#d97706",
    legend: [{ c: "#d97706", l: "Duraklama Dönemi Sınırları" }],
    events: [
      {
        year: 1590,
        title: "Ferhat Paşa Antlaşması",
        city: "İstanbul / İran",
        desc: "İran ile yapıldı; Osmanlı Devleti doğuda en geniş sınırlarına ulaştı.",
        tag: "Doğuda En Geniş Sınır",
        territory: [],
        x: 950.0,
        y: 220.0,
      },
      {
        year: 1596,
        title: "Haçova Meydan Savaşı",
        city: "Haçova (Macaristan)",
        desc: "III. Mehmed (Eğri Fatihi) Avusturya ordusunu büyük bir zaferle mağlup etti.",
        tag: "Zafer",
        territory: [],
        x: 15.0,
        y: 5.0,
      },
      {
        year: 1606,
        title: "Zitvatorok Antlaşması",
        city: "Zitvatorok",
        desc: "Avusturya kralı protokolde Osmanlı Padişahına denk sayıldı; Avusturya üzerindeki üstünlük bitti.",
        tag: "Diplomatik Eşitlik",
        territory: [],
        x: 25.0,
        y: 10.0,
      },
      {
        year: 1621,
        title: "Hotin Seferi",
        city: "Hotin (Ukrayna)",
        desc: "Genç Osman (II. Osman) Yeniçerilerin disiplinsizliğini gördü ve Ocağı kaldırma kararı aldı.",
        tag: "Islahat Düşüncesi",
        territory: [],
        x: 150.0,
        y: -20.0,
      },
      {
        year: 1639,
        title: "Kasr-ı Şirin Antlaşması",
        city: "Kasr-ı Şirin (İran)",
        desc: "IV. Murad (Bağdat Fatihi) İran ile imzaladı; bugünkü Türkiye-İran sınırı büyük oranda çizildi.",
        tag: "Kalıcı Sınır",
        territory: [],
        x: 960.0,
        y: 240.0,
      },
      {
        year: 1669,
        title: "Girit'in Fethi",
        city: "Girit Adası",
        desc: "Fazıl Ahmet Paşa 24 yıl süren kuşatma sonrasında Girit'i fethederek Akdeniz'e bağladı.",
        tag: "Son Deniz Fethi",
        territory: [],
        x: 200.0,
        y: 410.0,
      },
      {
        year: 1672,
        title: "Bucaş Antlaşması",
        city: "Bucaş (Polonya)",
        desc: "Lehistan ile yapıldı; Osmanlı Devleti batıda en geniş sınırlarına ulaştı.",
        tag: "Batıda En Geniş Sınır",
        territory: [],
        x: 120.0,
        y: -15.0,
      },
      {
        year: 1683,
        title: "II. Viyana Kuşatması",
        city: "Viyana (Avusturya)",
        desc: "Merzifonlu Kara Mustafa Paşa komutasındaki kuşatma başarısız oldu; Kutsal İttifak kuruldu.",
        tag: "Geri Çekilme Başlangıcı",
        territory: [],
        x: 5.0,
        y: 0.0,
      },
      {
        year: 1699,
        title: "Karlofça Antlaşması",
        city: "Karlofça (Sırbistan)",
        desc: "Osmanlı batıda ilk kez büyük miktarda toprak kaybetti; Duraklama bitti, Gerileme dönemi başladı.",
        tag: "Büyük Toprak Kaybı",
        territory: [],
        x: 20.0,
        y: 15.0,
      },
    ],
  },

  /* ---------------- OSMANLI GERİLEME DÖNEMİ ---------------- */
  {
    id: "osmanli-gerileme",
    navLabel: "Osmanlı Gerileme (1700-1792)",
    mode: "territory",
    title: "Osmanlı Devleti Gerileme Dönemi ve Islahatlar",
    subtitle: "7 kilit olay · Prut'tan Yaş Antlaşmasına (1700-1792)",
    showYear: true,
    color: "#2563eb",
    legend: [{ c: "#2563eb", l: "Gerileme Dönemi Olayları" }],
    events: [
      {
        year: 1711,
        title: "Prut Antlaşması",
        city: "Prut Nehri (Moldova)",
        desc: "Baltacı Mehmed Paşa Rusya'yı mağlup etti; Karlofça ile kaybedilen yerleri geri alma ümidi doğdu.",
        tag: "Geri Alma Ümidi",
        territory: [],
        x: 180.0,
        y: 10.0,
      },
      {
        year: 1718,
        title: "Pasarofça Antlaşması & Lale Devri",
        city: "Pasarofça / İstanbul",
        desc: "Avrupa'nın üstünlüğü kabul edildi. III. Ahmet ve Nevşehirli Damat İbrahim Paşa ile Lale Devri ıslahatları başladı.",
        tag: "Lale Devri",
        territory: [],
        x: 190.4,
        y: 69.8,
      },
      {
        year: 1730,
        title: "Patrona Halil İsyanı",
        city: "İstanbul",
        desc: "İsyan sonucu Lale Devri sona erdi; III. Ahmet tahttan indirildi.",
        tag: "İsyan",
        territory: [],
        x: 190.4,
        y: 69.8,
      },
      {
        year: 1739,
        title: "Belgrat Antlaşması",
        city: "Belgrat",
        desc: "I. Mahmud döneminde Fransız subay Comte de Bonneval (Humbaracı Ahmet) orduyu ıslah etti; 18. yy'ın son kazançlı antlaşması yapıldı.",
        tag: "Son Kazançlı Antlaşma",
        territory: [],
        x: 20.0,
        y: 10.0,
      },
      {
        year: 1774,
        title: "Küçük Kaynarca Antlaşması",
        city: "Küçük Kaynarca (Bulgaristan)",
        desc: "Kırım bağımsız oldu; Rusya'ya savaş tazminatı verilerek Ortodoksları koruma hakkı tanındı.",
        tag: "Ağır Şartlı Antlaşma",
        territory: [],
        x: 80.0,
        y: 30.0,
      },
      {
        year: 1789,
        title: "Fransız İhtilali'nin Etkileri",
        city: "Paris / İstanbul",
        desc: "Milliyetçilik akımı Osmanlı gibi çok uluslu imparatorluklarda azınlık isyanlarını tetikledi.",
        tag: "Dünya Etkisi",
        territory: [],
        x: 100.0,
        y: 100.0,
      },
      {
        year: 1792,
        title: "Yaş Antlaşması",
        city: "Yaş (Romanya)",
        desc: "Kırım'ın Rusya'ya ait olduğu resmen kabul edildi; Gerileme dönemi bitti, Dağılma dönemi başladı.",
        tag: "Dağılma Başlangıcı",
        territory: [],
        x: 160.0,
        y: 20.0,
      },
    ],
  },

  /* ---------------- OSMANLI DAĞILMA VE YIKILIŞ DÖNEMİ ---------------- */
  {
    id: "osmanli-dagilma",
    navLabel: "Osmanlı Dağılma & Yıkılış (1792-1922)",
    mode: "territory",
    title: "Osmanlı Devleti Dağılma ve Yıkılış Dönemi",
    subtitle: "12 dönüm noktası · Sened-i İttifak'tan Saltanatın Kaldırılmasına (1792-1922)",
    showYear: true,
    color: "#7c3aed",
    legend: [{ c: "#7c3aed", l: "Dağılma & Yıkılış Dönemi" }],
    events: [
      {
        year: 1808,
        title: "Sened-i İttifak",
        city: "İstanbul",
        desc: "II. Mahmud ile Ayanlar arasında imzalandı. Padişahın yetkileri ilk kez sınırlandırıldı (İlk demokratikleşme).",
        tag: "Demokratikleşme",
        territory: [],
        x: 190.4,
        y: 69.8,
      },
      {
        year: 1826,
        title: "Vaka-i Hayriye (Yeniçeri Ocağının Kaldırılması)",
        city: "İstanbul",
        desc: "II. Mahmud bozulmuş Yeniçeri Ocağı'nı kaldırdı; yerine Asakir-i Mansure-i Muhammediye ordusu kuruldu.",
        tag: "Askeri Islahat",
        territory: [],
        x: 190.4,
        y: 69.8,
      },
      {
        year: 1829,
        title: "Edirne Antlaşması",
        city: "Edirne",
        desc: "Yunanistan bağımsızlığını kazanarak Osmanlı'dan ayrılan ilk azınlık millet oldu.",
        tag: "İlk Bağımsızlık",
        territory: [],
        x: 50.0,
        y: 40.0,
      },
      {
        year: 1839,
        title: "Tanzimat Fermanı (Gülhane Hatt-ı Hümayunu)",
        city: "İstanbul",
        desc: "Mustafa Reşit Paşa okudu. Kanun üstünlüğü kabul edildi; din ayrımı gözetmeksizin herkes eşit sayıldı.",
        tag: "Kanun Üstünlüğü",
        territory: [],
        x: 190.4,
        y: 69.8,
      },
      {
        year: 1856,
        title: "Islahat Fermanı & Kırım Savaşı",
        city: "İstanbul / Kırım",
        desc: "Azınlıklara geniş haklar verildi. İngiltere'den ilk dış borç alındı; Paris Antlaşmasıyla Osmanlı Avrupa devleti sayıldı.",
        tag: "İlk Dış Borç",
        territory: [],
        x: 190.4,
        y: 69.8,
      },
      {
        year: 1876,
        title: "I. Meşrutiyet & Kanun-ı Esasi",
        city: "İstanbul",
        desc: "II. Abdülhamid ve Jön Türkler ilk anayasayı (Kanun-ı Esasi) ilan etti; Meclis-i Mebusan açıldı.",
        tag: "İlk Anayasa",
        territory: [],
        x: 190.4,
        y: 69.8,
      },
      {
        year: 1878,
        title: "93 Harbi ve Berlin Antlaşması",
        city: "Berlin / Erzurum / Yeşilköy",
        desc: "Sırbistan, Karadağ ve Romanya bağımsız oldu; Kars, Ardahan, Batum Rusya'ya bırakıldı.",
        tag: "Büyük Kayıp",
        territory: ["Erzurum", "Kars", "Ardahan"],
        color: "#7c3aed",
        x: 853.4,
        y: 140.8,
      },
      {
        year: 1908,
        title: "II. Meşrutiyet & 31 Mart Vakası (1909)",
        city: "İstanbul / Selanik",
        desc: "Reval Görüşmelerinden sonra İttihatçılar Meşrutiyeti tekrar ilan etti. Rejime karşı ilk 31 Mart İsyanını Mustafa Kemal'in Kurmay Başkanı olduğu Hareket Ordusu bastırdı.",
        tag: "Rejim İsyanı",
        territory: [],
        x: 190.4,
        y: 69.8,
      },
      {
        year: 1911,
        title: "Trablusgarp Savaşı ve Uşi Antlaşması",
        city: "Trablusgarp (Libya)",
        desc: "Mustafa Kemal Derne ve Tobruk'ta destan yazdı; Uşi ile Kuzey Afrika'daki son toprak kaybedildi.",
        tag: "Son Afrika Toprağı",
        territory: [],
        x: 300.0,
        y: 410.0,
      },
      {
        year: 1912,
        title: "Balkan Savaşları (1912-1913)",
        city: "Balkanlar / Edirne",
        desc: "Batı Trakya, Makedonya, Ege Adaları kaybedildi. Enver Paşa II. Balkan Savaşında Edirne'yi geri aldı.",
        tag: "Balkan Kaybı",
        territory: [],
        x: 50.0,
        y: 40.0,
      },
      {
        year: 1915,
        title: "I. Dünya Savaşı & Çanakkale Zaferi",
        city: "Çanakkale / Kut'ül Amare",
        desc: "Mustafa Kemal Anafartalar'da 'Ben size taarruzu değil ölmeyi emrediyorum' dedi. Çanakkale geçilmedi!",
        tag: "Destansı Zafer",
        territory: ["Çanakkale"],
        color: "#7c3aed",
        x: 62.5,
        y: 161.0,
      },
      {
        year: 1922,
        title: "Saltanatın Kaldırılması (1 Kasım 1922)",
        city: "Ankara (TBMM)",
        desc: "TBMM kararıyla 623 yıllık Osmanlı Devleti hukuken ve resmen sona erdi.",
        tag: "Osmanlı'nın Sonu",
        territory: [],
        x: 367.9,
        y: 181.3,
      },
    ],
  },

  /* ---------------- OSMANLI DEVLET TEŞKİLATI (ŞEMA) ---------------- */
  {
    id: "osmanli-teskilat",
    navLabel: "Osmanlı Devlet Teşkilatı",
    mode: "diagram",
    title: "Osmanlı Devlet Teşkilatı ve Kültür Medeniyet",
    subtitle: "Divan-ı Hümayun, Seyfiye, İlmiye, Kalemiye ve Taşra Hiyerarşisi",
    showYear: false,
    color: "#c99a3c",
    legend: [
      { c: "#c99a3c", l: "Padişah / Merkez" },
      { c: "#1f5f7a", l: "Seyfiye (Yürütme/Asker)" },
      { c: "#7c3aed", l: "İlmiye (Yargı/Eğitim)" },
      { c: "#2f8f5b", l: "Kalemiye (Bürokrasi/Maliye)" },
    ],
  },

  {
    id: "ekonomi",
    navLabel: "Ekonomi & Ticaret",
    mode: "points",
    title: "Anadolu Selçuklu'da Ekonomi ve Ticaret",
    subtitle: "8 merkez · kervan yolları, limanlar, Ahilik",
    showYear: false,
    color: "#2f8f5b",
    legend: [{ c: "#2f8f5b", l: "Ticaret / kervan merkezi" }],
    events: [
      {
        title: "Konya",
        city: "Başkent",
        desc: "Başkent olarak zanaat, ticaret ve kervan yollarının buluştuğu merkezdi.",
        tag: "Merkez",
        x: 355.7,
        y: 283.9,
      },
      {
        title: "Kayseri",
        city: "Kervan Yolu Kavşağı",
        desc: "İç Anadolu'yu Doğu'ya bağlayan kervan yollarının kesişim noktasıydı, tüccarların uğrak yeriydi.",
        tag: "Ticaret",
        x: 511.9,
        y: 226.3,
      },
      {
        title: "Sivas",
        city: "Kervan Yolu",
        desc: "Anadolu'yu Orta Doğu ve İran'a bağlayan ana kervan yolu üzerindeydi.",
        tag: "Ticaret",
        x: 592.2,
        y: 158,
      },
      {
        title: "Sultanhanı",
        city: "Aksaray-Konya arası",
        desc: "Konya-Aksaray-Kayseri hattındaki en büyük kervansaraylardan biri, I. Alaeddin Keykubad döneminde yapıldı.",
        tag: "Kervansaray",
        x: 410.8,
        y: 258,
      },
      {
        title: "Antalya",
        city: "Akdeniz Limanı",
        desc: "Venedik ve Cenevizli tüccarlarla yapılan deniz ticaretinin ana limanıydı.",
        tag: "Deniz Ticareti",
        x: 263.3,
        y: 349.4,
      },
      {
        title: "Alanya",
        city: "Tersane",
        desc: "I. Alaeddin Keykubad'ın kurdurduğu tersane burada bulunuyordu; donanma ve deniz ticareti üssüydü.",
        tag: "Donanma",
        x: 330.4,
        y: 373.1,
      },
      {
        title: "Sinop",
        city: "Karadeniz Limanı",
        desc: "Karadeniz'e açılan ana liman; kürk ve kereste ticaretinde önemliydi.",
        tag: "Deniz Ticareti",
        x: 495,
        y: 5.3,
      },
      {
        title: "Kırşehir",
        city: "Ahi Evran",
        desc: "Ahi Evran'ın kurduğu Ahilik teşkilatının merkeziydi; esnaf ve zanaatkârları örgütledi.",
        tag: "Ahilik",
        x: 443.3,
        y: 198.5,
      },
    ],
  },
  {
    id: "kultur",
    navLabel: "Bilim, Kültür & Mimari",
    mode: "points",
    title: "Anadolu Selçuklu'da Bilim, Kültür ve Mimari",
    subtitle: "7 merkez · medreseler, külliyeler, isimler",
    showYear: false,
    color: "#7c3aed",
    legend: [{ c: "#7c3aed", l: "Kültür / mimari merkezi" }],
    events: [
      {
        title: "Konya - Mevlana",
        city: "Mesnevi ve Mevlevilik",
        desc: "Mevlana Celaleddin-i Rumi burada yaşadı, Mesnevi'yi yazdı; İnce Minareli ve Karatay medreseleri buradadır.",
        tag: "Tasavvuf",
        x: 355.7,
        y: 283.9,
      },
      {
        title: "Akşehir - Nasreddin Hoca",
        city: "Konya",
        desc: "Nasreddin Hoca'nın yaşadığı ve mezarının bulunduğu yer; halk hikâyeleriyle ünlüdür.",
        tag: "Halk Kültürü",
        x: 300.1,
        y: 251.5,
      },
      {
        title: "Sivas Medreseleri",
        city: "Gök Medrese, Çifte Minareli",
        desc: "Selçuklu medrese mimarisinin en gösterişli örnekleri burada inşa edildi.",
        tag: "Mimari",
        x: 592.2,
        y: 158,
      },
      {
        title: "Divriği Ulu Camii",
        city: "Sivas",
        desc: "Taş işçiliğiyle ünlü cami ve darüşşifa kompleksi; UNESCO Dünya Mirası listesindedir.",
        tag: "Mimari",
        x: 649.7,
        y: 183.8,
      },
      {
        title: "Erzurum Medreseleri",
        city: "Çifte Minareli Medrese",
        desc: "Doğu Anadolu'daki en önemli Selçuklu medrese yapılarından biridir.",
        tag: "Mimari",
        x: 814.4,
        y: 147.6,
      },
      {
        title: "Kayseri Külliyeleri",
        city: "Hunad Hatun, Döner Kümbet",
        desc: "Selçuklu dönemi külliye ve kümbet mimarisinin önemli örnekleri burada bulunur.",
        tag: "Mimari",
        x: 511.9,
        y: 226.3,
      },
      {
        title: "Kırşehir - Ahi Evran / Aşık Paşa",
        city: "Ahilik ve tasavvuf kültürü",
        desc: "Ahi Evran ve şair Aşık Paşa'nın merkezi; hem zanaat hem tasavvuf kültürü burada gelişti.",
        tag: "Tasavvuf",
        x: 443.3,
        y: 198.5,
      },
    ],
  },
  {
    id: "beylikler",
    navLabel: "1308 Sonrası Beylikler",
    mode: "territory",
    title: "1308 Sonrası: Anadolu Beylikleri",
    subtitle: "8 önemli beylik · devlet dağılınca ortaya çıkan yapı",
    showYear: false,
    color: "#8c2a1f",
    legend: null,
    events: [
      {
        title: "Karamanoğulları",
        city: "Konya / Karaman",
        desc: "En güçlü beylikti; 1277'de Türkçeyi resmî dil ilan etti. Selçuklu mirasına en çok sahip çıkan beylikti.",
        tag: "Beylik",
        territory: ["Konya", "Karaman", "Niğde"],
        color: "#8c2a1f",
        x: 390.5,
        y: 319,
      },
      {
        title: "Germiyanoğulları",
        city: "Kütahya",
        desc: "İç Batı Anadolu'da güçlü bir beylikti, Kütahya merkezliydi.",
        tag: "Beylik",
        territory: ["Kütahya", "Uşak"],
        color: "#6b4226",
        x: 225.4,
        y: 180.2,
      },
      {
        title: "Aydınoğulları",
        city: "Aydın / İzmir",
        desc: "Ege kıyısında denizcilikte güçlendi, Bizans ve Venediklilerle ilişkileri vardı.",
        tag: "Beylik",
        territory: ["Aydın", "İzmir"],
        color: "#2e6b3e",
        x: 95.7,
        y: 275.4,
      },
      {
        title: "Saruhanoğulları",
        city: "Manisa",
        desc: "Ege bölgesinde Manisa merkezli, denizci bir beylikti.",
        tag: "Beylik",
        territory: ["Manisa"],
        color: "#a4770b",
        x: 91.9,
        y: 234.4,
      },
      {
        title: "Menteşeoğulları",
        city: "Muğla",
        desc: "Güneybatı Ege'de denizcilikle uğraşan, en eski beyliklerden biriydi.",
        tag: "Beylik",
        territory: ["Muğla"],
        color: "#5b3a8c",
        x: 140.7,
        y: 328.1,
      },
      {
        title: "Candaroğulları",
        city: "Kastamonu / Sinop",
        desc: "Karadeniz kıyısında, Kastamonu ve Sinop merkezli uzun ömürlü bir beylikti.",
        tag: "Beylik",
        territory: ["Kastamonu", "Sinop"],
        color: "#1f5f7a",
        x: 423.1,
        y: 48.7,
      },
      {
        title: "Osmanoğulları",
        city: "Söğüt / Bilecik",
        desc: "Başlangıçta küçük bir uç beyliğiydi; zamanla diğer beylikleri birleştirip Osmanlı Devleti'ne dönüştü.",
        tag: "Beylik",
        territory: ["Bilecik"],
        color: "#c99a3c",
        x: 235.3,
        y: 141.4,
      },
      {
        title: "Dulkadiroğulları",
        city: "Elbistan / Maraş",
        desc: "Güneydoğuda Memlük ve Osmanlı arasında denge siyareti izleyen bir beylikti.",
        tag: "Beylik",
        territory: ["Kahramanmaraş"],
        color: "#3a3a3a",
        x: 601.9,
        y: 261.6,
      },
    ],
  },
];
