import type { GeoPin } from "./types.js";

export const TURKEY_TOURISM_UNESCO: GeoPin[] = [
  {
    name: "Göbeklitepe Arkeolojik Alanı (2018)",
    city: "Şanlıurfa",
    x: 720.0,
    y: 310.0,
    description: "Tarihin sıfır noktası kabul edilen, dünyanın bilinen en eski tapınak kompleksidir (UNESCO).",
    examTip: "İnsanlık tarihinin ilk inanç ve tapınak merkezidir; UNESCO Dünya Kültür Mirası listesindedir.",
  },
  {
    name: "Efes Antik Kenti & Meryem Ana (2015)",
    city: "İzmir (Selçuk)",
    x: 120.0,
    y: 250.0,
    description: "Artemis Tapınağı, Celcus Kütüphanesi ve antik tiyatrosuyla dünyanın en görkemli antik liman kentidir.",
    examTip: "UNESCO mirasıdır. Menderes'in alüvyon dolguları nedeniyle liman özelliğini yitirmiştir.",
  },
  {
    name: "Göreme Milli Parkı & Kapadokya (1985)",
    city: "Nevşehir / Aksaray",
    x: 480.0,
    y: 230.0,
    description: "Volkanik tüf kayaların erozyonuyla oluşan peribacaları ve yeraltı şehirleri karma mirasıdır.",
    examTip: "Türkiye'nin UNESCO'daki ilk karma (Kültürel ve Doğal) miras alanıdır.",
  },
  {
    name: "Nemrut Dağı Heykelleri (1987)",
    city: "Adıyaman (Kahta)",
    x: 670.0,
    y: 250.0,
    description: "Kommagene Krallığı'na ait dev tanrı heykelleri ve tümülüsün yer aldığı kutsal alandır.",
    examTip: "Güneşin doğuşu ve batışının izlendiği UNESCO kültür mirası dağımızdır.",
  },
  {
    name: "Çatalhöyük Neolitik Kenti (2012)",
    city: "Konya (Çumra)",
    x: 390.0,
    y: 270.0,
    description: "İnsanlığın ilk yerleşik hayata geçtiği, sokaksız bitişik evlerden oluşan Neolitik kenttir.",
    examTip: "İlk ev mimarisi ve toplu köy yaşamının dünyadaki en önemli kanıtıdır (UNESCO).",
  },
  {
    name: "Ani Arkeolojik Alanı (2016)",
    city: "Kars",
    x: 910.0,
    y: 85.0,
    description: "Binbir Kiliseli Şehir olarak bilinen İpek Yolu üzerindeki surlarla çevrili antik kenttir.",
    examTip: "Türkiye-Ermenistan sınırında Arpaçay kenarında yer alan UNESCO mirasımızdır.",
  },
  {
    name: "Divriği Ulu Camii ve Darüşşifası (1985)",
    city: "Sivas (Divriği)",
    x: 650.0,
    y: 160.0,
    description: "Mengücekliler dönemine ait, eşsiz taş işçiliği ve gölge kapı motifleriyle bilinen eserdir.",
    examTip: "Türkiye'nin UNESCO listesine giren İLK mimari kültürel eseridir.",
  },
  {
    name: "Gordion Antik Kenti (2023)",
    city: "Ankara (Polatlı)",
    x: 330.0,
    y: 150.0,
    description: "Frigya Krallığı'nın başkenti ve Kral Midas'ın tümülüsünün bulunduğu antik kenttir.",
    examTip: "Türkiye'nin UNESCO Dünya Miras Listesi'ne eklenen en son kültür miraslarındandır (2023).",
  },
  {
    name: "Hattuşa - Hitit Başkenti (1986)",
    city: "Çorum (Boğazköy)",
    x: 480.0,
    y: 130.0,
    description: "Hitit İmparatorluğu'nun başkenti, Yazılıkaya açık hava tapınağı ve Kadeş Antlaşması metinlerinin evidir.",
    examTip: "Hitit medeniyetinin kalbidir; UNESCO Dünya Kültür Mirasıdır.",
  },
  {
    name: "Sümela Manastırı",
    city: "Trabzon (Maçka)",
    x: 740.0,
    y: 80.0,
    description: "Karadağ yamaçlarındaki dik kayalıklara oyulmuş tarihi Rum Ortodoks manastırıdır.",
    examTip: "Doğu Karadeniz'in en çok ziyaret edilen kültür ve inanç turizmi merkezidir.",
  },
];
