/**
 * agentActionPolicy.ts
 * Deterministic Security & Policy Engine for Web Agent DOM Actions.
 * Enforces Zod schema validation, Read-Only vs Mutating Side-Effect classification,
 * Tab/URL context binding, and user confirmation gating for sensitive interactions.
 */

import { z } from "zod";

export const AgentActionTypeSchema = z.enum([
  "click",
  "type",
  "scroll",
  "extract",
  "highlight",
]);

export const AgentActionPayloadSchema = z.object({
  actionType: AgentActionTypeSchema,
  selector: z
    .string()
    .max(500)
    .refine((sel) => !/javascript:|data:/i.test(sel), {
      message: "Dangerous pseudo-protocol in selector",
    })
    .optional(),
  targetText: z.string().max(200).optional(),
  textValue: z.string().max(5000).optional(),
  direction: z.enum(["up", "down"]).optional(),
});

export const AgentActionBatchSchema = z
  .array(AgentActionPayloadSchema)
  .min(1, "At least one action is required")
  .max(5, "Maximum 5 actions allowed per proposal");

export type AgentActionPayload = z.infer<typeof AgentActionPayloadSchema>;

export type ActionSecurityClassification = "READ_ONLY" | "MUTATING_SIDE_EFFECT";

export interface ActionContextBinding {
  expectedTabId?: number;
  expectedUrl?: string;
  actualTabId?: number;
  actualUrl?: string;
}

export interface ActionPolicyEvaluation {
  allowed: boolean;
  classification: ActionSecurityClassification;
  requiresUserConfirmation: boolean;
  sanitizedActions: AgentActionPayload[];
  reason?: string;
}

/**
 * Classifies an individual action type into READ_ONLY or MUTATING_SIDE_EFFECT.
 */
export function classifyAction(
  actionType: z.infer<typeof AgentActionTypeSchema>,
): ActionSecurityClassification {
  switch (actionType) {
    case "click":
    case "type":
      return "MUTATING_SIDE_EFFECT";
    case "scroll":
    case "extract":
    case "highlight":
    default:
      return "READ_ONLY";
  }
}

export interface TabBindingOptions {
  /**
   * When true, requires an exact URL match (pathname + search) in addition to
   * the origin match. Hash fragments are ignored because intra-page anchors do
   * not change document identity. Use this for MUTATING actions to close the
   * same-origin navigation race (e.g. /checkout -> /confirmation SPA transition).
   */
  requireExactUrl?: boolean;
}

/**
 * Compares two URLs by origin, and optionally by full path+query.
 * Returns null when valid, or a rejection reason string.
 */
function compareUrls(
  expectedUrl: string,
  actualUrl: string,
  requireExactUrl: boolean,
): string | null {
  let expOrigin: string;
  let actOrigin: string;
  let expNorm: string;
  let actNorm: string;
  try {
    const expUrlObj = new URL(expectedUrl);
    const actUrlObj = new URL(actualUrl);
    expOrigin = expUrlObj.origin;
    actOrigin = actUrlObj.origin;
    expNorm = `${expUrlObj.pathname}${expUrlObj.search}`;
    actNorm = `${actUrlObj.pathname}${actUrlObj.search}`;
  } catch {
    return "Malformed URL in context binding";
  }

  if (expOrigin !== actOrigin) {
    return `Origin mismatch: proposal originated from ${expOrigin}, but active tab is ${actOrigin}`;
  }

  if (requireExactUrl && expNorm !== actNorm) {
    return `URL mismatch: proposal was bound to ${expNorm}, but active tab navigated to ${actNorm}`;
  }

  return null;
}

/**
 * Validates whether the active tab matches the tab where the action proposal was originated.
 * Prevents executing actions if the user switched tabs, navigated to a different origin,
 * or (for mutating actions) navigated to a different document within the same origin.
 */
export function validateTabBinding(
  binding?: ActionContextBinding,
  options?: TabBindingOptions,
): {
  valid: boolean;
  reason?: string;
} {
  if (!binding) {return { valid: true };}

  const { expectedTabId, actualTabId, expectedUrl, actualUrl } = binding;

  if (
    expectedTabId !== undefined &&
    actualTabId !== undefined &&
    expectedTabId !== actualTabId
  ) {
    return {
      valid: false,
      reason: `Tab mismatch: proposal was generated for tab ${expectedTabId}, but current active tab is ${actualTabId}`,
    };
  }

  if (expectedUrl && actualUrl) {
    const reason = compareUrls(
      expectedUrl,
      actualUrl,
      options?.requireExactUrl === true,
    );
    if (reason) {
      return { valid: false, reason };
    }
  }

  return { valid: true };
}

/**
 * Evaluates an untrusted action proposal generated by LLM.
 * Returns sanitized actions, required confirmation level, or rejection reason.
 */
export function evaluateActionProposal(
  rawActions: unknown,
  context?: ActionContextBinding,
): ActionPolicyEvaluation {
  // 1. Normalize single action to array
  const actionArray = Array.isArray(rawActions) ? rawActions : [rawActions];

  // 2. Zod Schema Validation
  const parseResult = AgentActionBatchSchema.safeParse(actionArray);
  if (!parseResult.success) {
    return {
      allowed: false,
      classification: "MUTATING_SIDE_EFFECT",
      requiresUserConfirmation: true,
      sanitizedActions: [],
      reason: `Action validation failed: ${parseResult.error.issues.map((i) => i.message).join(", ")}`,
    };
  }

  const actions = parseResult.data;

  // 3. Classify whole batch (if any action is mutating, entire batch requires confirmation)
  const hasSideEffect = actions.some(
    (act) => classifyAction(act.actionType) === "MUTATING_SIDE_EFFECT",
  );

  // 4. Tab / URL Binding Validation — mutating actions require exact URL match
  const tabCheck = validateTabBinding(context, {
    requireExactUrl: hasSideEffect,
  });
  if (!tabCheck.valid) {
    return {
      allowed: false,
      classification: hasSideEffect ? "MUTATING_SIDE_EFFECT" : "READ_ONLY",
      requiresUserConfirmation: hasSideEffect,
      sanitizedActions: [],
      reason: tabCheck.reason,
    };
  }

  return {
    allowed: true,
    classification: hasSideEffect ? "MUTATING_SIDE_EFFECT" : "READ_ONLY",
    requiresUserConfirmation: hasSideEffect,
    sanitizedActions: actions,
  };
}

/**
 * Strictly verifies whether an HTML element is genuinely editable.
 * Prevents typing arbitrary text into arbitrary <div>, <p>, or non-input elements.
 * Works across iframes and testing environments.
 */
export function isElementEditable(el: unknown): boolean {
  if (!el || typeof el !== "object") {return false;}

  const target = el as {
    tagName?: string;
    type?: string;
    isContentEditable?: boolean;
    getAttribute?: (attr: string) => string | null;
    classList?: { contains: (cls: string) => boolean };
  };

  const tag = (target.tagName || "").toUpperCase();

  // Standard input elements (excluding buttons/checkboxes/radio)
  if (tag === "INPUT") {
    const nonTextTypes = [
      "button",
      "checkbox",
      "radio",
      "submit",
      "reset",
      "file",
      "image",
      "hidden",
    ];
    return !nonTextTypes.includes((target.type || "").toLowerCase());
  }

  if (tag === "TEXTAREA") {
    return true;
  }

  // True contenteditable
  if (
    target.isContentEditable ||
    target.getAttribute?.("contenteditable") === "true"
  ) {
    return true;
  }

  // Explicit ARIA textbox role
  if (target.getAttribute?.("role") === "textbox") {
    return true;
  }

  // Known rich text editor container classes (e.g. Quill, ProseMirror)
  const isRichEditor = Boolean(
    target.classList?.contains("ql-editor") ||
      target.classList?.contains("ProseMirror") ||
      target.classList?.contains("notion-page-content") ||
      target.classList?.contains("public-DraftEditor-content"),
  );

  return isRichEditor;
}
